from typing import Protocol


class BlobStore(Protocol):
    def put_bytes(self, key: str, data: bytes) -> str: ...
    def get_bytes(self, key: str) -> bytes: ...
    def exists(self, key: str) -> bool: ...
    def delete(self, key: str) -> None: ...
    def delete_prefix(self, prefix: str) -> None:
        """Every blob under a folder key ending in "/". A missing folder is a no-op."""
        ...
