from typing import Protocol


class StructureNormalizer(Protocol):
    def canonicalize(self, smiles: str) -> str | None: ...
    def has_multiple_components(self, smiles: str) -> bool: ...
    def murcko_scaffold(self, smiles: str) -> str: ...
