/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateFolderBody,
  FolderListResponse,
  FolderResponse,
  HTTPValidationError,
  ListFoldersApiV1FoldersGetParams,
  RenameFolderBody
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * @summary List Folders
 */
export const listFoldersApiV1FoldersGet = (
    params: ListFoldersApiV1FoldersGetParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<FolderListResponse>(
      {url: `/api/v1/folders`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListFoldersApiV1FoldersGetQueryKey = (params?: ListFoldersApiV1FoldersGetParams,) => {
    return [
    `/api/v1/folders`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListFoldersApiV1FoldersGetQueryOptions = <TData = Awaited<ReturnType<typeof listFoldersApiV1FoldersGet>>, TError = HTTPValidationError>(params: ListFoldersApiV1FoldersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFoldersApiV1FoldersGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListFoldersApiV1FoldersGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listFoldersApiV1FoldersGet>>> = ({ signal }) => listFoldersApiV1FoldersGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listFoldersApiV1FoldersGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListFoldersApiV1FoldersGetQueryResult = NonNullable<Awaited<ReturnType<typeof listFoldersApiV1FoldersGet>>>
export type ListFoldersApiV1FoldersGetQueryError = HTTPValidationError


export function useListFoldersApiV1FoldersGet<TData = Awaited<ReturnType<typeof listFoldersApiV1FoldersGet>>, TError = HTTPValidationError>(
 params: ListFoldersApiV1FoldersGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFoldersApiV1FoldersGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFoldersApiV1FoldersGet>>,
          TError,
          Awaited<ReturnType<typeof listFoldersApiV1FoldersGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFoldersApiV1FoldersGet<TData = Awaited<ReturnType<typeof listFoldersApiV1FoldersGet>>, TError = HTTPValidationError>(
 params: ListFoldersApiV1FoldersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFoldersApiV1FoldersGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFoldersApiV1FoldersGet>>,
          TError,
          Awaited<ReturnType<typeof listFoldersApiV1FoldersGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFoldersApiV1FoldersGet<TData = Awaited<ReturnType<typeof listFoldersApiV1FoldersGet>>, TError = HTTPValidationError>(
 params: ListFoldersApiV1FoldersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFoldersApiV1FoldersGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Folders
 */

export function useListFoldersApiV1FoldersGet<TData = Awaited<ReturnType<typeof listFoldersApiV1FoldersGet>>, TError = HTTPValidationError>(
 params: ListFoldersApiV1FoldersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFoldersApiV1FoldersGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListFoldersApiV1FoldersGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create Folder
 */
export const createFolderApiV1FoldersPost = (
    createFolderBody: CreateFolderBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<FolderResponse>(
      {url: `/api/v1/folders`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createFolderBody, signal
    },
      );
    }
  


export const getCreateFolderApiV1FoldersPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFolderApiV1FoldersPost>>, TError,{data: CreateFolderBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createFolderApiV1FoldersPost>>, TError,{data: CreateFolderBody}, TContext> => {

const mutationKey = ['createFolderApiV1FoldersPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createFolderApiV1FoldersPost>>, {data: CreateFolderBody}> = (props) => {
          const {data} = props ?? {};

          return  createFolderApiV1FoldersPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateFolderApiV1FoldersPostMutationResult = NonNullable<Awaited<ReturnType<typeof createFolderApiV1FoldersPost>>>
    export type CreateFolderApiV1FoldersPostMutationBody = CreateFolderBody
    export type CreateFolderApiV1FoldersPostMutationError = HTTPValidationError

    /**
 * @summary Create Folder
 */
export const useCreateFolderApiV1FoldersPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFolderApiV1FoldersPost>>, TError,{data: CreateFolderBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createFolderApiV1FoldersPost>>,
        TError,
        {data: CreateFolderBody},
        TContext
      > => {

      const mutationOptions = getCreateFolderApiV1FoldersPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Rename Folder
 */
export const renameFolderApiV1FoldersFolderIdPatch = (
    folderId: string,
    renameFolderBody: RenameFolderBody,
 ) => {
      
      
      return customInstance<FolderResponse>(
      {url: `/api/v1/folders/${folderId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: renameFolderBody
    },
      );
    }
  


export const getRenameFolderApiV1FoldersFolderIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof renameFolderApiV1FoldersFolderIdPatch>>, TError,{folderId: string;data: RenameFolderBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof renameFolderApiV1FoldersFolderIdPatch>>, TError,{folderId: string;data: RenameFolderBody}, TContext> => {

const mutationKey = ['renameFolderApiV1FoldersFolderIdPatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof renameFolderApiV1FoldersFolderIdPatch>>, {folderId: string;data: RenameFolderBody}> = (props) => {
          const {folderId,data} = props ?? {};

          return  renameFolderApiV1FoldersFolderIdPatch(folderId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RenameFolderApiV1FoldersFolderIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof renameFolderApiV1FoldersFolderIdPatch>>>
    export type RenameFolderApiV1FoldersFolderIdPatchMutationBody = RenameFolderBody
    export type RenameFolderApiV1FoldersFolderIdPatchMutationError = HTTPValidationError

    /**
 * @summary Rename Folder
 */
export const useRenameFolderApiV1FoldersFolderIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof renameFolderApiV1FoldersFolderIdPatch>>, TError,{folderId: string;data: RenameFolderBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof renameFolderApiV1FoldersFolderIdPatch>>,
        TError,
        {folderId: string;data: RenameFolderBody},
        TContext
      > => {

      const mutationOptions = getRenameFolderApiV1FoldersFolderIdPatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete Folder
 */
export const deleteFolderApiV1FoldersFolderIdDelete = (
    folderId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/folders/${folderId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteFolderApiV1FoldersFolderIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFolderApiV1FoldersFolderIdDelete>>, TError,{folderId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteFolderApiV1FoldersFolderIdDelete>>, TError,{folderId: string}, TContext> => {

const mutationKey = ['deleteFolderApiV1FoldersFolderIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteFolderApiV1FoldersFolderIdDelete>>, {folderId: string}> = (props) => {
          const {folderId} = props ?? {};

          return  deleteFolderApiV1FoldersFolderIdDelete(folderId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteFolderApiV1FoldersFolderIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteFolderApiV1FoldersFolderIdDelete>>>
    
    export type DeleteFolderApiV1FoldersFolderIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Folder
 */
export const useDeleteFolderApiV1FoldersFolderIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFolderApiV1FoldersFolderIdDelete>>, TError,{folderId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteFolderApiV1FoldersFolderIdDelete>>,
        TError,
        {folderId: string},
        TContext
      > => {

      const mutationOptions = getDeleteFolderApiV1FoldersFolderIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    