/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ChemCellarImportResponse,
  ChemCellarProtocolResponse,
  ChemCellarRunResponse,
  HTTPValidationError
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * @summary List Chemcellar Protocols
 */
export const listChemcellarProtocolsApiV1ChemcellarProtocolsGet = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<ChemCellarProtocolResponse[]>(
      {url: `/api/v1/chemcellar/protocols`, method: 'GET', signal
    },
      );
    }
  



export const getListChemcellarProtocolsApiV1ChemcellarProtocolsGetQueryKey = () => {
    return [
    `/api/v1/chemcellar/protocols`
    ] as const;
    }

    
export const getListChemcellarProtocolsApiV1ChemcellarProtocolsGetQueryOptions = <TData = Awaited<ReturnType<typeof listChemcellarProtocolsApiV1ChemcellarProtocolsGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listChemcellarProtocolsApiV1ChemcellarProtocolsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListChemcellarProtocolsApiV1ChemcellarProtocolsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listChemcellarProtocolsApiV1ChemcellarProtocolsGet>>> = ({ signal }) => listChemcellarProtocolsApiV1ChemcellarProtocolsGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listChemcellarProtocolsApiV1ChemcellarProtocolsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListChemcellarProtocolsApiV1ChemcellarProtocolsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listChemcellarProtocolsApiV1ChemcellarProtocolsGet>>>
export type ListChemcellarProtocolsApiV1ChemcellarProtocolsGetQueryError = unknown


export function useListChemcellarProtocolsApiV1ChemcellarProtocolsGet<TData = Awaited<ReturnType<typeof listChemcellarProtocolsApiV1ChemcellarProtocolsGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listChemcellarProtocolsApiV1ChemcellarProtocolsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listChemcellarProtocolsApiV1ChemcellarProtocolsGet>>,
          TError,
          Awaited<ReturnType<typeof listChemcellarProtocolsApiV1ChemcellarProtocolsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListChemcellarProtocolsApiV1ChemcellarProtocolsGet<TData = Awaited<ReturnType<typeof listChemcellarProtocolsApiV1ChemcellarProtocolsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listChemcellarProtocolsApiV1ChemcellarProtocolsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listChemcellarProtocolsApiV1ChemcellarProtocolsGet>>,
          TError,
          Awaited<ReturnType<typeof listChemcellarProtocolsApiV1ChemcellarProtocolsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListChemcellarProtocolsApiV1ChemcellarProtocolsGet<TData = Awaited<ReturnType<typeof listChemcellarProtocolsApiV1ChemcellarProtocolsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listChemcellarProtocolsApiV1ChemcellarProtocolsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Chemcellar Protocols
 */

export function useListChemcellarProtocolsApiV1ChemcellarProtocolsGet<TData = Awaited<ReturnType<typeof listChemcellarProtocolsApiV1ChemcellarProtocolsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listChemcellarProtocolsApiV1ChemcellarProtocolsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListChemcellarProtocolsApiV1ChemcellarProtocolsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary List Chemcellar Runs
 */
export const listChemcellarRunsApiV1ChemcellarProtocolsProtocolIdRunsGet = (
    protocolId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ChemCellarRunResponse[]>(
      {url: `/api/v1/chemcellar/protocols/${protocolId}/runs`, method: 'GET', signal
    },
      );
    }
  



export const getListChemcellarRunsApiV1ChemcellarProtocolsProtocolIdRunsGetQueryKey = (protocolId?: string,) => {
    return [
    `/api/v1/chemcellar/protocols/${protocolId}/runs`
    ] as const;
    }

    
export const getListChemcellarRunsApiV1ChemcellarProtocolsProtocolIdRunsGetQueryOptions = <TData = Awaited<ReturnType<typeof listChemcellarRunsApiV1ChemcellarProtocolsProtocolIdRunsGet>>, TError = HTTPValidationError>(protocolId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listChemcellarRunsApiV1ChemcellarProtocolsProtocolIdRunsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListChemcellarRunsApiV1ChemcellarProtocolsProtocolIdRunsGetQueryKey(protocolId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listChemcellarRunsApiV1ChemcellarProtocolsProtocolIdRunsGet>>> = ({ signal }) => listChemcellarRunsApiV1ChemcellarProtocolsProtocolIdRunsGet(protocolId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(protocolId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listChemcellarRunsApiV1ChemcellarProtocolsProtocolIdRunsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListChemcellarRunsApiV1ChemcellarProtocolsProtocolIdRunsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listChemcellarRunsApiV1ChemcellarProtocolsProtocolIdRunsGet>>>
export type ListChemcellarRunsApiV1ChemcellarProtocolsProtocolIdRunsGetQueryError = HTTPValidationError


export function useListChemcellarRunsApiV1ChemcellarProtocolsProtocolIdRunsGet<TData = Awaited<ReturnType<typeof listChemcellarRunsApiV1ChemcellarProtocolsProtocolIdRunsGet>>, TError = HTTPValidationError>(
 protocolId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listChemcellarRunsApiV1ChemcellarProtocolsProtocolIdRunsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listChemcellarRunsApiV1ChemcellarProtocolsProtocolIdRunsGet>>,
          TError,
          Awaited<ReturnType<typeof listChemcellarRunsApiV1ChemcellarProtocolsProtocolIdRunsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListChemcellarRunsApiV1ChemcellarProtocolsProtocolIdRunsGet<TData = Awaited<ReturnType<typeof listChemcellarRunsApiV1ChemcellarProtocolsProtocolIdRunsGet>>, TError = HTTPValidationError>(
 protocolId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listChemcellarRunsApiV1ChemcellarProtocolsProtocolIdRunsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listChemcellarRunsApiV1ChemcellarProtocolsProtocolIdRunsGet>>,
          TError,
          Awaited<ReturnType<typeof listChemcellarRunsApiV1ChemcellarProtocolsProtocolIdRunsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListChemcellarRunsApiV1ChemcellarProtocolsProtocolIdRunsGet<TData = Awaited<ReturnType<typeof listChemcellarRunsApiV1ChemcellarProtocolsProtocolIdRunsGet>>, TError = HTTPValidationError>(
 protocolId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listChemcellarRunsApiV1ChemcellarProtocolsProtocolIdRunsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Chemcellar Runs
 */

export function useListChemcellarRunsApiV1ChemcellarProtocolsProtocolIdRunsGet<TData = Awaited<ReturnType<typeof listChemcellarRunsApiV1ChemcellarProtocolsProtocolIdRunsGet>>, TError = HTTPValidationError>(
 protocolId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listChemcellarRunsApiV1ChemcellarProtocolsProtocolIdRunsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListChemcellarRunsApiV1ChemcellarProtocolsProtocolIdRunsGetQueryOptions(protocolId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Import Chemcellar Run
 */
export const importChemcellarRunApiV1ChemcellarRunsRunIdImportPost = (
    runId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ChemCellarImportResponse>(
      {url: `/api/v1/chemcellar/runs/${runId}/import`, method: 'POST', signal
    },
      );
    }
  


export const getImportChemcellarRunApiV1ChemcellarRunsRunIdImportPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importChemcellarRunApiV1ChemcellarRunsRunIdImportPost>>, TError,{runId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof importChemcellarRunApiV1ChemcellarRunsRunIdImportPost>>, TError,{runId: string}, TContext> => {

const mutationKey = ['importChemcellarRunApiV1ChemcellarRunsRunIdImportPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof importChemcellarRunApiV1ChemcellarRunsRunIdImportPost>>, {runId: string}> = (props) => {
          const {runId} = props ?? {};

          return  importChemcellarRunApiV1ChemcellarRunsRunIdImportPost(runId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ImportChemcellarRunApiV1ChemcellarRunsRunIdImportPostMutationResult = NonNullable<Awaited<ReturnType<typeof importChemcellarRunApiV1ChemcellarRunsRunIdImportPost>>>
    
    export type ImportChemcellarRunApiV1ChemcellarRunsRunIdImportPostMutationError = HTTPValidationError

    /**
 * @summary Import Chemcellar Run
 */
export const useImportChemcellarRunApiV1ChemcellarRunsRunIdImportPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importChemcellarRunApiV1ChemcellarRunsRunIdImportPost>>, TError,{runId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof importChemcellarRunApiV1ChemcellarRunsRunIdImportPost>>,
        TError,
        {runId: string},
        TContext
      > => {

      const mutationOptions = getImportChemcellarRunApiV1ChemcellarRunsRunIdImportPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    