/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CollectionResponse,
  CreateCollectionBody,
  ExportCollectionApiV1CollectionsCollectionIdExportGetParams,
  HTTPValidationError,
  ListCollectionsApiV1CollectionsGetParams,
  PaginatedResponseCollectionResponse
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * @summary Create Collection
 */
export const createCollectionApiV1CollectionsPost = (
    createCollectionBody: CreateCollectionBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CollectionResponse>(
      {url: `/api/v1/collections`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCollectionBody, signal
    },
      );
    }
  


export const getCreateCollectionApiV1CollectionsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCollectionApiV1CollectionsPost>>, TError,{data: CreateCollectionBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createCollectionApiV1CollectionsPost>>, TError,{data: CreateCollectionBody}, TContext> => {

const mutationKey = ['createCollectionApiV1CollectionsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCollectionApiV1CollectionsPost>>, {data: CreateCollectionBody}> = (props) => {
          const {data} = props ?? {};

          return  createCollectionApiV1CollectionsPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCollectionApiV1CollectionsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createCollectionApiV1CollectionsPost>>>
    export type CreateCollectionApiV1CollectionsPostMutationBody = CreateCollectionBody
    export type CreateCollectionApiV1CollectionsPostMutationError = HTTPValidationError

    /**
 * @summary Create Collection
 */
export const useCreateCollectionApiV1CollectionsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCollectionApiV1CollectionsPost>>, TError,{data: CreateCollectionBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createCollectionApiV1CollectionsPost>>,
        TError,
        {data: CreateCollectionBody},
        TContext
      > => {

      const mutationOptions = getCreateCollectionApiV1CollectionsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Declared before `/{collection_id}` so the empty path is not swallowed by
the id route -- Starlette matches in declaration order.
 * @summary List Collections
 */
export const listCollectionsApiV1CollectionsGet = (
    params?: ListCollectionsApiV1CollectionsGetParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PaginatedResponseCollectionResponse>(
      {url: `/api/v1/collections`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListCollectionsApiV1CollectionsGetQueryKey = (params?: ListCollectionsApiV1CollectionsGetParams,) => {
    return [
    `/api/v1/collections`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListCollectionsApiV1CollectionsGetQueryOptions = <TData = Awaited<ReturnType<typeof listCollectionsApiV1CollectionsGet>>, TError = HTTPValidationError>(params?: ListCollectionsApiV1CollectionsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCollectionsApiV1CollectionsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCollectionsApiV1CollectionsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listCollectionsApiV1CollectionsGet>>> = ({ signal }) => listCollectionsApiV1CollectionsGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listCollectionsApiV1CollectionsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListCollectionsApiV1CollectionsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listCollectionsApiV1CollectionsGet>>>
export type ListCollectionsApiV1CollectionsGetQueryError = HTTPValidationError


export function useListCollectionsApiV1CollectionsGet<TData = Awaited<ReturnType<typeof listCollectionsApiV1CollectionsGet>>, TError = HTTPValidationError>(
 params: undefined |  ListCollectionsApiV1CollectionsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCollectionsApiV1CollectionsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCollectionsApiV1CollectionsGet>>,
          TError,
          Awaited<ReturnType<typeof listCollectionsApiV1CollectionsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCollectionsApiV1CollectionsGet<TData = Awaited<ReturnType<typeof listCollectionsApiV1CollectionsGet>>, TError = HTTPValidationError>(
 params?: ListCollectionsApiV1CollectionsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCollectionsApiV1CollectionsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCollectionsApiV1CollectionsGet>>,
          TError,
          Awaited<ReturnType<typeof listCollectionsApiV1CollectionsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCollectionsApiV1CollectionsGet<TData = Awaited<ReturnType<typeof listCollectionsApiV1CollectionsGet>>, TError = HTTPValidationError>(
 params?: ListCollectionsApiV1CollectionsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCollectionsApiV1CollectionsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Collections
 */

export function useListCollectionsApiV1CollectionsGet<TData = Awaited<ReturnType<typeof listCollectionsApiV1CollectionsGet>>, TError = HTTPValidationError>(
 params?: ListCollectionsApiV1CollectionsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCollectionsApiV1CollectionsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListCollectionsApiV1CollectionsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get Collection
 */
export const getCollectionApiV1CollectionsCollectionIdGet = (
    collectionId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CollectionResponse>(
      {url: `/api/v1/collections/${collectionId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetCollectionApiV1CollectionsCollectionIdGetQueryKey = (collectionId?: string,) => {
    return [
    `/api/v1/collections/${collectionId}`
    ] as const;
    }

    
export const getGetCollectionApiV1CollectionsCollectionIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getCollectionApiV1CollectionsCollectionIdGet>>, TError = HTTPValidationError>(collectionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCollectionApiV1CollectionsCollectionIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCollectionApiV1CollectionsCollectionIdGetQueryKey(collectionId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCollectionApiV1CollectionsCollectionIdGet>>> = ({ signal }) => getCollectionApiV1CollectionsCollectionIdGet(collectionId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(collectionId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCollectionApiV1CollectionsCollectionIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCollectionApiV1CollectionsCollectionIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getCollectionApiV1CollectionsCollectionIdGet>>>
export type GetCollectionApiV1CollectionsCollectionIdGetQueryError = HTTPValidationError


export function useGetCollectionApiV1CollectionsCollectionIdGet<TData = Awaited<ReturnType<typeof getCollectionApiV1CollectionsCollectionIdGet>>, TError = HTTPValidationError>(
 collectionId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCollectionApiV1CollectionsCollectionIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCollectionApiV1CollectionsCollectionIdGet>>,
          TError,
          Awaited<ReturnType<typeof getCollectionApiV1CollectionsCollectionIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCollectionApiV1CollectionsCollectionIdGet<TData = Awaited<ReturnType<typeof getCollectionApiV1CollectionsCollectionIdGet>>, TError = HTTPValidationError>(
 collectionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCollectionApiV1CollectionsCollectionIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCollectionApiV1CollectionsCollectionIdGet>>,
          TError,
          Awaited<ReturnType<typeof getCollectionApiV1CollectionsCollectionIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCollectionApiV1CollectionsCollectionIdGet<TData = Awaited<ReturnType<typeof getCollectionApiV1CollectionsCollectionIdGet>>, TError = HTTPValidationError>(
 collectionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCollectionApiV1CollectionsCollectionIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Collection
 */

export function useGetCollectionApiV1CollectionsCollectionIdGet<TData = Awaited<ReturnType<typeof getCollectionApiV1CollectionsCollectionIdGet>>, TError = HTTPValidationError>(
 collectionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCollectionApiV1CollectionsCollectionIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCollectionApiV1CollectionsCollectionIdGetQueryOptions(collectionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Export Collection
 */
export const exportCollectionApiV1CollectionsCollectionIdExportGet = (
    collectionId: string,
    params: ExportCollectionApiV1CollectionsCollectionIdExportGetParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/collections/${collectionId}/export`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getExportCollectionApiV1CollectionsCollectionIdExportGetQueryKey = (collectionId?: string,
    params?: ExportCollectionApiV1CollectionsCollectionIdExportGetParams,) => {
    return [
    `/api/v1/collections/${collectionId}/export`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getExportCollectionApiV1CollectionsCollectionIdExportGetQueryOptions = <TData = Awaited<ReturnType<typeof exportCollectionApiV1CollectionsCollectionIdExportGet>>, TError = HTTPValidationError>(collectionId: string,
    params: ExportCollectionApiV1CollectionsCollectionIdExportGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportCollectionApiV1CollectionsCollectionIdExportGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getExportCollectionApiV1CollectionsCollectionIdExportGetQueryKey(collectionId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof exportCollectionApiV1CollectionsCollectionIdExportGet>>> = ({ signal }) => exportCollectionApiV1CollectionsCollectionIdExportGet(collectionId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(collectionId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof exportCollectionApiV1CollectionsCollectionIdExportGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ExportCollectionApiV1CollectionsCollectionIdExportGetQueryResult = NonNullable<Awaited<ReturnType<typeof exportCollectionApiV1CollectionsCollectionIdExportGet>>>
export type ExportCollectionApiV1CollectionsCollectionIdExportGetQueryError = HTTPValidationError


export function useExportCollectionApiV1CollectionsCollectionIdExportGet<TData = Awaited<ReturnType<typeof exportCollectionApiV1CollectionsCollectionIdExportGet>>, TError = HTTPValidationError>(
 collectionId: string,
    params: ExportCollectionApiV1CollectionsCollectionIdExportGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportCollectionApiV1CollectionsCollectionIdExportGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportCollectionApiV1CollectionsCollectionIdExportGet>>,
          TError,
          Awaited<ReturnType<typeof exportCollectionApiV1CollectionsCollectionIdExportGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExportCollectionApiV1CollectionsCollectionIdExportGet<TData = Awaited<ReturnType<typeof exportCollectionApiV1CollectionsCollectionIdExportGet>>, TError = HTTPValidationError>(
 collectionId: string,
    params: ExportCollectionApiV1CollectionsCollectionIdExportGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportCollectionApiV1CollectionsCollectionIdExportGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportCollectionApiV1CollectionsCollectionIdExportGet>>,
          TError,
          Awaited<ReturnType<typeof exportCollectionApiV1CollectionsCollectionIdExportGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExportCollectionApiV1CollectionsCollectionIdExportGet<TData = Awaited<ReturnType<typeof exportCollectionApiV1CollectionsCollectionIdExportGet>>, TError = HTTPValidationError>(
 collectionId: string,
    params: ExportCollectionApiV1CollectionsCollectionIdExportGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportCollectionApiV1CollectionsCollectionIdExportGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Export Collection
 */

export function useExportCollectionApiV1CollectionsCollectionIdExportGet<TData = Awaited<ReturnType<typeof exportCollectionApiV1CollectionsCollectionIdExportGet>>, TError = HTTPValidationError>(
 collectionId: string,
    params: ExportCollectionApiV1CollectionsCollectionIdExportGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportCollectionApiV1CollectionsCollectionIdExportGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getExportCollectionApiV1CollectionsCollectionIdExportGetQueryOptions(collectionId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




