/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BlobPutResponse,
  ClaimResponse,
  DatasetEnvelope,
  HTTPValidationError,
  ProtocolEnvelope,
  RunEnvelope,
  RunUpdateEnvelope,
  RunUpdateResponse
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * @summary Claim
 */
export const claimApiV1RunnerClaimPost = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<ClaimResponse>(
      {url: `/api/v1/runner/claim`, method: 'POST', signal
    },
      );
    }
  


export const getClaimApiV1RunnerClaimPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof claimApiV1RunnerClaimPost>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof claimApiV1RunnerClaimPost>>, TError,void, TContext> => {

const mutationKey = ['claimApiV1RunnerClaimPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof claimApiV1RunnerClaimPost>>, void> = () => {
          

          return  claimApiV1RunnerClaimPost()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ClaimApiV1RunnerClaimPostMutationResult = NonNullable<Awaited<ReturnType<typeof claimApiV1RunnerClaimPost>>>
    
    export type ClaimApiV1RunnerClaimPostMutationError = unknown

    /**
 * @summary Claim
 */
export const useClaimApiV1RunnerClaimPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof claimApiV1RunnerClaimPost>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof claimApiV1RunnerClaimPost>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getClaimApiV1RunnerClaimPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get Run
 */
export const getRunApiV1RunnerRunsRunIdGet = (
    runId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<RunEnvelope>(
      {url: `/api/v1/runner/runs/${runId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetRunApiV1RunnerRunsRunIdGetQueryKey = (runId?: string,) => {
    return [
    `/api/v1/runner/runs/${runId}`
    ] as const;
    }

    
export const getGetRunApiV1RunnerRunsRunIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getRunApiV1RunnerRunsRunIdGet>>, TError = HTTPValidationError>(runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRunApiV1RunnerRunsRunIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRunApiV1RunnerRunsRunIdGetQueryKey(runId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRunApiV1RunnerRunsRunIdGet>>> = ({ signal }) => getRunApiV1RunnerRunsRunIdGet(runId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(runId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRunApiV1RunnerRunsRunIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRunApiV1RunnerRunsRunIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getRunApiV1RunnerRunsRunIdGet>>>
export type GetRunApiV1RunnerRunsRunIdGetQueryError = HTTPValidationError


export function useGetRunApiV1RunnerRunsRunIdGet<TData = Awaited<ReturnType<typeof getRunApiV1RunnerRunsRunIdGet>>, TError = HTTPValidationError>(
 runId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRunApiV1RunnerRunsRunIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRunApiV1RunnerRunsRunIdGet>>,
          TError,
          Awaited<ReturnType<typeof getRunApiV1RunnerRunsRunIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRunApiV1RunnerRunsRunIdGet<TData = Awaited<ReturnType<typeof getRunApiV1RunnerRunsRunIdGet>>, TError = HTTPValidationError>(
 runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRunApiV1RunnerRunsRunIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRunApiV1RunnerRunsRunIdGet>>,
          TError,
          Awaited<ReturnType<typeof getRunApiV1RunnerRunsRunIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRunApiV1RunnerRunsRunIdGet<TData = Awaited<ReturnType<typeof getRunApiV1RunnerRunsRunIdGet>>, TError = HTTPValidationError>(
 runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRunApiV1RunnerRunsRunIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Run
 */

export function useGetRunApiV1RunnerRunsRunIdGet<TData = Awaited<ReturnType<typeof getRunApiV1RunnerRunsRunIdGet>>, TError = HTTPValidationError>(
 runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRunApiV1RunnerRunsRunIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRunApiV1RunnerRunsRunIdGetQueryOptions(runId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update Run
 */
export const updateRunApiV1RunnerRunsRunIdPost = (
    runId: string,
    runUpdateEnvelope: RunUpdateEnvelope,
 signal?: AbortSignal
) => {
      
      
      return customInstance<RunUpdateResponse>(
      {url: `/api/v1/runner/runs/${runId}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: runUpdateEnvelope, signal
    },
      );
    }
  


export const getUpdateRunApiV1RunnerRunsRunIdPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRunApiV1RunnerRunsRunIdPost>>, TError,{runId: string;data: RunUpdateEnvelope}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateRunApiV1RunnerRunsRunIdPost>>, TError,{runId: string;data: RunUpdateEnvelope}, TContext> => {

const mutationKey = ['updateRunApiV1RunnerRunsRunIdPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateRunApiV1RunnerRunsRunIdPost>>, {runId: string;data: RunUpdateEnvelope}> = (props) => {
          const {runId,data} = props ?? {};

          return  updateRunApiV1RunnerRunsRunIdPost(runId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateRunApiV1RunnerRunsRunIdPostMutationResult = NonNullable<Awaited<ReturnType<typeof updateRunApiV1RunnerRunsRunIdPost>>>
    export type UpdateRunApiV1RunnerRunsRunIdPostMutationBody = RunUpdateEnvelope
    export type UpdateRunApiV1RunnerRunsRunIdPostMutationError = HTTPValidationError

    /**
 * @summary Update Run
 */
export const useUpdateRunApiV1RunnerRunsRunIdPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRunApiV1RunnerRunsRunIdPost>>, TError,{runId: string;data: RunUpdateEnvelope}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateRunApiV1RunnerRunsRunIdPost>>,
        TError,
        {runId: string;data: RunUpdateEnvelope},
        TContext
      > => {

      const mutationOptions = getUpdateRunApiV1RunnerRunsRunIdPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get Dataset
 */
export const getDatasetApiV1RunnerRunsRunIdDatasetGet = (
    runId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<DatasetEnvelope>(
      {url: `/api/v1/runner/runs/${runId}/dataset`, method: 'GET', signal
    },
      );
    }
  



export const getGetDatasetApiV1RunnerRunsRunIdDatasetGetQueryKey = (runId?: string,) => {
    return [
    `/api/v1/runner/runs/${runId}/dataset`
    ] as const;
    }

    
export const getGetDatasetApiV1RunnerRunsRunIdDatasetGetQueryOptions = <TData = Awaited<ReturnType<typeof getDatasetApiV1RunnerRunsRunIdDatasetGet>>, TError = HTTPValidationError>(runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDatasetApiV1RunnerRunsRunIdDatasetGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDatasetApiV1RunnerRunsRunIdDatasetGetQueryKey(runId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDatasetApiV1RunnerRunsRunIdDatasetGet>>> = ({ signal }) => getDatasetApiV1RunnerRunsRunIdDatasetGet(runId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(runId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDatasetApiV1RunnerRunsRunIdDatasetGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDatasetApiV1RunnerRunsRunIdDatasetGetQueryResult = NonNullable<Awaited<ReturnType<typeof getDatasetApiV1RunnerRunsRunIdDatasetGet>>>
export type GetDatasetApiV1RunnerRunsRunIdDatasetGetQueryError = HTTPValidationError


export function useGetDatasetApiV1RunnerRunsRunIdDatasetGet<TData = Awaited<ReturnType<typeof getDatasetApiV1RunnerRunsRunIdDatasetGet>>, TError = HTTPValidationError>(
 runId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDatasetApiV1RunnerRunsRunIdDatasetGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDatasetApiV1RunnerRunsRunIdDatasetGet>>,
          TError,
          Awaited<ReturnType<typeof getDatasetApiV1RunnerRunsRunIdDatasetGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDatasetApiV1RunnerRunsRunIdDatasetGet<TData = Awaited<ReturnType<typeof getDatasetApiV1RunnerRunsRunIdDatasetGet>>, TError = HTTPValidationError>(
 runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDatasetApiV1RunnerRunsRunIdDatasetGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDatasetApiV1RunnerRunsRunIdDatasetGet>>,
          TError,
          Awaited<ReturnType<typeof getDatasetApiV1RunnerRunsRunIdDatasetGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDatasetApiV1RunnerRunsRunIdDatasetGet<TData = Awaited<ReturnType<typeof getDatasetApiV1RunnerRunsRunIdDatasetGet>>, TError = HTTPValidationError>(
 runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDatasetApiV1RunnerRunsRunIdDatasetGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Dataset
 */

export function useGetDatasetApiV1RunnerRunsRunIdDatasetGet<TData = Awaited<ReturnType<typeof getDatasetApiV1RunnerRunsRunIdDatasetGet>>, TError = HTTPValidationError>(
 runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDatasetApiV1RunnerRunsRunIdDatasetGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDatasetApiV1RunnerRunsRunIdDatasetGetQueryOptions(runId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get Protocol
 */
export const getProtocolApiV1RunnerRunsRunIdProtocolGet = (
    runId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ProtocolEnvelope>(
      {url: `/api/v1/runner/runs/${runId}/protocol`, method: 'GET', signal
    },
      );
    }
  



export const getGetProtocolApiV1RunnerRunsRunIdProtocolGetQueryKey = (runId?: string,) => {
    return [
    `/api/v1/runner/runs/${runId}/protocol`
    ] as const;
    }

    
export const getGetProtocolApiV1RunnerRunsRunIdProtocolGetQueryOptions = <TData = Awaited<ReturnType<typeof getProtocolApiV1RunnerRunsRunIdProtocolGet>>, TError = HTTPValidationError>(runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProtocolApiV1RunnerRunsRunIdProtocolGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProtocolApiV1RunnerRunsRunIdProtocolGetQueryKey(runId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProtocolApiV1RunnerRunsRunIdProtocolGet>>> = ({ signal }) => getProtocolApiV1RunnerRunsRunIdProtocolGet(runId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(runId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProtocolApiV1RunnerRunsRunIdProtocolGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProtocolApiV1RunnerRunsRunIdProtocolGetQueryResult = NonNullable<Awaited<ReturnType<typeof getProtocolApiV1RunnerRunsRunIdProtocolGet>>>
export type GetProtocolApiV1RunnerRunsRunIdProtocolGetQueryError = HTTPValidationError


export function useGetProtocolApiV1RunnerRunsRunIdProtocolGet<TData = Awaited<ReturnType<typeof getProtocolApiV1RunnerRunsRunIdProtocolGet>>, TError = HTTPValidationError>(
 runId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProtocolApiV1RunnerRunsRunIdProtocolGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProtocolApiV1RunnerRunsRunIdProtocolGet>>,
          TError,
          Awaited<ReturnType<typeof getProtocolApiV1RunnerRunsRunIdProtocolGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProtocolApiV1RunnerRunsRunIdProtocolGet<TData = Awaited<ReturnType<typeof getProtocolApiV1RunnerRunsRunIdProtocolGet>>, TError = HTTPValidationError>(
 runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProtocolApiV1RunnerRunsRunIdProtocolGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProtocolApiV1RunnerRunsRunIdProtocolGet>>,
          TError,
          Awaited<ReturnType<typeof getProtocolApiV1RunnerRunsRunIdProtocolGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProtocolApiV1RunnerRunsRunIdProtocolGet<TData = Awaited<ReturnType<typeof getProtocolApiV1RunnerRunsRunIdProtocolGet>>, TError = HTTPValidationError>(
 runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProtocolApiV1RunnerRunsRunIdProtocolGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Protocol
 */

export function useGetProtocolApiV1RunnerRunsRunIdProtocolGet<TData = Awaited<ReturnType<typeof getProtocolApiV1RunnerRunsRunIdProtocolGet>>, TError = HTTPValidationError>(
 runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProtocolApiV1RunnerRunsRunIdProtocolGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProtocolApiV1RunnerRunsRunIdProtocolGetQueryOptions(runId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create Protocol
 */
export const createProtocolApiV1RunnerRunsRunIdProtocolPost = (
    runId: string,
    protocolEnvelope: ProtocolEnvelope,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/runner/runs/${runId}/protocol`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: protocolEnvelope, signal
    },
      );
    }
  


export const getCreateProtocolApiV1RunnerRunsRunIdProtocolPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProtocolApiV1RunnerRunsRunIdProtocolPost>>, TError,{runId: string;data: ProtocolEnvelope}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createProtocolApiV1RunnerRunsRunIdProtocolPost>>, TError,{runId: string;data: ProtocolEnvelope}, TContext> => {

const mutationKey = ['createProtocolApiV1RunnerRunsRunIdProtocolPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProtocolApiV1RunnerRunsRunIdProtocolPost>>, {runId: string;data: ProtocolEnvelope}> = (props) => {
          const {runId,data} = props ?? {};

          return  createProtocolApiV1RunnerRunsRunIdProtocolPost(runId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateProtocolApiV1RunnerRunsRunIdProtocolPostMutationResult = NonNullable<Awaited<ReturnType<typeof createProtocolApiV1RunnerRunsRunIdProtocolPost>>>
    export type CreateProtocolApiV1RunnerRunsRunIdProtocolPostMutationBody = ProtocolEnvelope
    export type CreateProtocolApiV1RunnerRunsRunIdProtocolPostMutationError = HTTPValidationError

    /**
 * @summary Create Protocol
 */
export const useCreateProtocolApiV1RunnerRunsRunIdProtocolPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProtocolApiV1RunnerRunsRunIdProtocolPost>>, TError,{runId: string;data: ProtocolEnvelope}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProtocolApiV1RunnerRunsRunIdProtocolPost>>,
        TError,
        {runId: string;data: ProtocolEnvelope},
        TContext
      > => {

      const mutationOptions = getCreateProtocolApiV1RunnerRunsRunIdProtocolPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get Blob
 */
export const getBlobApiV1RunnerRunsRunIdBlobsKeyGet = (
    runId: string,
    key: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/runner/runs/${runId}/blobs/${key}`, method: 'GET', signal
    },
      );
    }
  



export const getGetBlobApiV1RunnerRunsRunIdBlobsKeyGetQueryKey = (runId?: string,
    key?: string,) => {
    return [
    `/api/v1/runner/runs/${runId}/blobs/${key}`
    ] as const;
    }

    
export const getGetBlobApiV1RunnerRunsRunIdBlobsKeyGetQueryOptions = <TData = Awaited<ReturnType<typeof getBlobApiV1RunnerRunsRunIdBlobsKeyGet>>, TError = HTTPValidationError>(runId: string,
    key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBlobApiV1RunnerRunsRunIdBlobsKeyGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBlobApiV1RunnerRunsRunIdBlobsKeyGetQueryKey(runId,key);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBlobApiV1RunnerRunsRunIdBlobsKeyGet>>> = ({ signal }) => getBlobApiV1RunnerRunsRunIdBlobsKeyGet(runId,key, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(runId && key), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBlobApiV1RunnerRunsRunIdBlobsKeyGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBlobApiV1RunnerRunsRunIdBlobsKeyGetQueryResult = NonNullable<Awaited<ReturnType<typeof getBlobApiV1RunnerRunsRunIdBlobsKeyGet>>>
export type GetBlobApiV1RunnerRunsRunIdBlobsKeyGetQueryError = HTTPValidationError


export function useGetBlobApiV1RunnerRunsRunIdBlobsKeyGet<TData = Awaited<ReturnType<typeof getBlobApiV1RunnerRunsRunIdBlobsKeyGet>>, TError = HTTPValidationError>(
 runId: string,
    key: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBlobApiV1RunnerRunsRunIdBlobsKeyGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBlobApiV1RunnerRunsRunIdBlobsKeyGet>>,
          TError,
          Awaited<ReturnType<typeof getBlobApiV1RunnerRunsRunIdBlobsKeyGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBlobApiV1RunnerRunsRunIdBlobsKeyGet<TData = Awaited<ReturnType<typeof getBlobApiV1RunnerRunsRunIdBlobsKeyGet>>, TError = HTTPValidationError>(
 runId: string,
    key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBlobApiV1RunnerRunsRunIdBlobsKeyGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBlobApiV1RunnerRunsRunIdBlobsKeyGet>>,
          TError,
          Awaited<ReturnType<typeof getBlobApiV1RunnerRunsRunIdBlobsKeyGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBlobApiV1RunnerRunsRunIdBlobsKeyGet<TData = Awaited<ReturnType<typeof getBlobApiV1RunnerRunsRunIdBlobsKeyGet>>, TError = HTTPValidationError>(
 runId: string,
    key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBlobApiV1RunnerRunsRunIdBlobsKeyGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Blob
 */

export function useGetBlobApiV1RunnerRunsRunIdBlobsKeyGet<TData = Awaited<ReturnType<typeof getBlobApiV1RunnerRunsRunIdBlobsKeyGet>>, TError = HTTPValidationError>(
 runId: string,
    key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBlobApiV1RunnerRunsRunIdBlobsKeyGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBlobApiV1RunnerRunsRunIdBlobsKeyGetQueryOptions(runId,key,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Put Blob
 */
export const putBlobApiV1RunnerRunsRunIdBlobsKeyPut = (
    runId: string,
    key: string,
 ) => {
      
      
      return customInstance<BlobPutResponse>(
      {url: `/api/v1/runner/runs/${runId}/blobs/${key}`, method: 'PUT'
    },
      );
    }
  


export const getPutBlobApiV1RunnerRunsRunIdBlobsKeyPutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putBlobApiV1RunnerRunsRunIdBlobsKeyPut>>, TError,{runId: string;key: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putBlobApiV1RunnerRunsRunIdBlobsKeyPut>>, TError,{runId: string;key: string}, TContext> => {

const mutationKey = ['putBlobApiV1RunnerRunsRunIdBlobsKeyPut'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putBlobApiV1RunnerRunsRunIdBlobsKeyPut>>, {runId: string;key: string}> = (props) => {
          const {runId,key} = props ?? {};

          return  putBlobApiV1RunnerRunsRunIdBlobsKeyPut(runId,key,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutBlobApiV1RunnerRunsRunIdBlobsKeyPutMutationResult = NonNullable<Awaited<ReturnType<typeof putBlobApiV1RunnerRunsRunIdBlobsKeyPut>>>
    
    export type PutBlobApiV1RunnerRunsRunIdBlobsKeyPutMutationError = HTTPValidationError

    /**
 * @summary Put Blob
 */
export const usePutBlobApiV1RunnerRunsRunIdBlobsKeyPut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putBlobApiV1RunnerRunsRunIdBlobsKeyPut>>, TError,{runId: string;key: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putBlobApiV1RunnerRunsRunIdBlobsKeyPut>>,
        TError,
        {runId: string;key: string},
        TContext
      > => {

      const mutationOptions = getPutBlobApiV1RunnerRunsRunIdBlobsKeyPutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    