/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  ListSweepsApiV1SweepsGetParams,
  SubmitSweepBody,
  SweepDetailResponse,
  SweepListResponse
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * @summary Submit Sweep
 */
export const submitSweepApiV1SweepsPost = (
    submitSweepBody: SubmitSweepBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<SweepDetailResponse>(
      {url: `/api/v1/sweeps`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: submitSweepBody, signal
    },
      );
    }
  


export const getSubmitSweepApiV1SweepsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof submitSweepApiV1SweepsPost>>, TError,{data: SubmitSweepBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof submitSweepApiV1SweepsPost>>, TError,{data: SubmitSweepBody}, TContext> => {

const mutationKey = ['submitSweepApiV1SweepsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof submitSweepApiV1SweepsPost>>, {data: SubmitSweepBody}> = (props) => {
          const {data} = props ?? {};

          return  submitSweepApiV1SweepsPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SubmitSweepApiV1SweepsPostMutationResult = NonNullable<Awaited<ReturnType<typeof submitSweepApiV1SweepsPost>>>
    export type SubmitSweepApiV1SweepsPostMutationBody = SubmitSweepBody
    export type SubmitSweepApiV1SweepsPostMutationError = HTTPValidationError

    /**
 * @summary Submit Sweep
 */
export const useSubmitSweepApiV1SweepsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof submitSweepApiV1SweepsPost>>, TError,{data: SubmitSweepBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof submitSweepApiV1SweepsPost>>,
        TError,
        {data: SubmitSweepBody},
        TContext
      > => {

      const mutationOptions = getSubmitSweepApiV1SweepsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List Sweeps
 */
export const listSweepsApiV1SweepsGet = (
    params?: ListSweepsApiV1SweepsGetParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<SweepListResponse>(
      {url: `/api/v1/sweeps`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListSweepsApiV1SweepsGetQueryKey = (params?: ListSweepsApiV1SweepsGetParams,) => {
    return [
    `/api/v1/sweeps`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListSweepsApiV1SweepsGetQueryOptions = <TData = Awaited<ReturnType<typeof listSweepsApiV1SweepsGet>>, TError = HTTPValidationError>(params?: ListSweepsApiV1SweepsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSweepsApiV1SweepsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSweepsApiV1SweepsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSweepsApiV1SweepsGet>>> = ({ signal }) => listSweepsApiV1SweepsGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSweepsApiV1SweepsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSweepsApiV1SweepsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listSweepsApiV1SweepsGet>>>
export type ListSweepsApiV1SweepsGetQueryError = HTTPValidationError


export function useListSweepsApiV1SweepsGet<TData = Awaited<ReturnType<typeof listSweepsApiV1SweepsGet>>, TError = HTTPValidationError>(
 params: undefined |  ListSweepsApiV1SweepsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSweepsApiV1SweepsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSweepsApiV1SweepsGet>>,
          TError,
          Awaited<ReturnType<typeof listSweepsApiV1SweepsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSweepsApiV1SweepsGet<TData = Awaited<ReturnType<typeof listSweepsApiV1SweepsGet>>, TError = HTTPValidationError>(
 params?: ListSweepsApiV1SweepsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSweepsApiV1SweepsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSweepsApiV1SweepsGet>>,
          TError,
          Awaited<ReturnType<typeof listSweepsApiV1SweepsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSweepsApiV1SweepsGet<TData = Awaited<ReturnType<typeof listSweepsApiV1SweepsGet>>, TError = HTTPValidationError>(
 params?: ListSweepsApiV1SweepsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSweepsApiV1SweepsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Sweeps
 */

export function useListSweepsApiV1SweepsGet<TData = Awaited<ReturnType<typeof listSweepsApiV1SweepsGet>>, TError = HTTPValidationError>(
 params?: ListSweepsApiV1SweepsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSweepsApiV1SweepsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListSweepsApiV1SweepsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get Sweep
 */
export const getSweepApiV1SweepsSweepIdGet = (
    sweepId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<SweepDetailResponse>(
      {url: `/api/v1/sweeps/${sweepId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetSweepApiV1SweepsSweepIdGetQueryKey = (sweepId?: string,) => {
    return [
    `/api/v1/sweeps/${sweepId}`
    ] as const;
    }

    
export const getGetSweepApiV1SweepsSweepIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getSweepApiV1SweepsSweepIdGet>>, TError = HTTPValidationError>(sweepId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSweepApiV1SweepsSweepIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSweepApiV1SweepsSweepIdGetQueryKey(sweepId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSweepApiV1SweepsSweepIdGet>>> = ({ signal }) => getSweepApiV1SweepsSweepIdGet(sweepId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(sweepId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSweepApiV1SweepsSweepIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSweepApiV1SweepsSweepIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getSweepApiV1SweepsSweepIdGet>>>
export type GetSweepApiV1SweepsSweepIdGetQueryError = HTTPValidationError


export function useGetSweepApiV1SweepsSweepIdGet<TData = Awaited<ReturnType<typeof getSweepApiV1SweepsSweepIdGet>>, TError = HTTPValidationError>(
 sweepId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSweepApiV1SweepsSweepIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSweepApiV1SweepsSweepIdGet>>,
          TError,
          Awaited<ReturnType<typeof getSweepApiV1SweepsSweepIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSweepApiV1SweepsSweepIdGet<TData = Awaited<ReturnType<typeof getSweepApiV1SweepsSweepIdGet>>, TError = HTTPValidationError>(
 sweepId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSweepApiV1SweepsSweepIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSweepApiV1SweepsSweepIdGet>>,
          TError,
          Awaited<ReturnType<typeof getSweepApiV1SweepsSweepIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSweepApiV1SweepsSweepIdGet<TData = Awaited<ReturnType<typeof getSweepApiV1SweepsSweepIdGet>>, TError = HTTPValidationError>(
 sweepId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSweepApiV1SweepsSweepIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Sweep
 */

export function useGetSweepApiV1SweepsSweepIdGet<TData = Awaited<ReturnType<typeof getSweepApiV1SweepsSweepIdGet>>, TError = HTTPValidationError>(
 sweepId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSweepApiV1SweepsSweepIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSweepApiV1SweepsSweepIdGetQueryOptions(sweepId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Cancel Sweep
 */
export const cancelSweepApiV1SweepsSweepIdCancelPost = (
    sweepId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/sweeps/${sweepId}/cancel`, method: 'POST', signal
    },
      );
    }
  


export const getCancelSweepApiV1SweepsSweepIdCancelPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelSweepApiV1SweepsSweepIdCancelPost>>, TError,{sweepId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof cancelSweepApiV1SweepsSweepIdCancelPost>>, TError,{sweepId: string}, TContext> => {

const mutationKey = ['cancelSweepApiV1SweepsSweepIdCancelPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cancelSweepApiV1SweepsSweepIdCancelPost>>, {sweepId: string}> = (props) => {
          const {sweepId} = props ?? {};

          return  cancelSweepApiV1SweepsSweepIdCancelPost(sweepId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CancelSweepApiV1SweepsSweepIdCancelPostMutationResult = NonNullable<Awaited<ReturnType<typeof cancelSweepApiV1SweepsSweepIdCancelPost>>>
    
    export type CancelSweepApiV1SweepsSweepIdCancelPostMutationError = HTTPValidationError

    /**
 * @summary Cancel Sweep
 */
export const useCancelSweepApiV1SweepsSweepIdCancelPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelSweepApiV1SweepsSweepIdCancelPost>>, TError,{sweepId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cancelSweepApiV1SweepsSweepIdCancelPost>>,
        TError,
        {sweepId: string},
        TContext
      > => {

      const mutationOptions = getCancelSweepApiV1SweepsSweepIdCancelPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    