/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  EngineManifestResponse
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * List all available engines with their condition specifications.

The response carries everything a form needs to render without any hardcoded
engine knowledge: for each engine, its id, name, description, supported tasks,
baseline flag, and all condition parameters (key, label, type, required, default,
bounds, options, help text).
 * @summary List Engines
 */
export const listEnginesApiV1EnginesGet = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<EngineManifestResponse[]>(
      {url: `/api/v1/engines`, method: 'GET', signal
    },
      );
    }
  



export const getListEnginesApiV1EnginesGetQueryKey = () => {
    return [
    `/api/v1/engines`
    ] as const;
    }

    
export const getListEnginesApiV1EnginesGetQueryOptions = <TData = Awaited<ReturnType<typeof listEnginesApiV1EnginesGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEnginesApiV1EnginesGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListEnginesApiV1EnginesGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listEnginesApiV1EnginesGet>>> = ({ signal }) => listEnginesApiV1EnginesGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listEnginesApiV1EnginesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListEnginesApiV1EnginesGetQueryResult = NonNullable<Awaited<ReturnType<typeof listEnginesApiV1EnginesGet>>>
export type ListEnginesApiV1EnginesGetQueryError = unknown


export function useListEnginesApiV1EnginesGet<TData = Awaited<ReturnType<typeof listEnginesApiV1EnginesGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEnginesApiV1EnginesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEnginesApiV1EnginesGet>>,
          TError,
          Awaited<ReturnType<typeof listEnginesApiV1EnginesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListEnginesApiV1EnginesGet<TData = Awaited<ReturnType<typeof listEnginesApiV1EnginesGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEnginesApiV1EnginesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEnginesApiV1EnginesGet>>,
          TError,
          Awaited<ReturnType<typeof listEnginesApiV1EnginesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListEnginesApiV1EnginesGet<TData = Awaited<ReturnType<typeof listEnginesApiV1EnginesGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEnginesApiV1EnginesGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Engines
 */

export function useListEnginesApiV1EnginesGet<TData = Awaited<ReturnType<typeof listEnginesApiV1EnginesGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEnginesApiV1EnginesGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListEnginesApiV1EnginesGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




