/** Class strings shared by every figure, all from design tokens, so theme switches need no JS. */
export const S = {
  text: "fill-secondary-foreground font-mono text-[10px]",
  textStrong: "fill-foreground font-mono text-[10px]",
  small: "fill-secondary-foreground font-mono text-[9px]",
  smallStrong: "fill-foreground font-mono text-[9px]",
  line: "fill-none stroke-muted-foreground/50",
  node: "fill-card stroke-muted-foreground/50",
  nodeOn: "fill-card stroke-chart-1",
  measured: "fill-chart-1",
  measuredLine: "fill-none stroke-chart-1",
  held: "fill-score-fair",
  heldLine: "fill-none stroke-score-fair",
  heldRing: "fill-card stroke-score-fair",
  pulse: "fill-chart-2",
  fit: "fill-none stroke-foreground",
  pred: "fill-card stroke-foreground",
  band: "fill-chart-1/15",
  box: "fill-card stroke-muted-foreground/50",
  boxOn: "fill-accent stroke-chart-1",
  ink: "fill-none stroke-foreground",
  inkFill: "fill-foreground",
  cardFill: "fill-card",
} as const;
