/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  ListProtocolsApiV1ProtocolsGetParams,
  PaginatedResponseProtocolResponse,
  ProtocolResponse,
  RunResponse,
  ScorecardResponse,
  TrainProtocolBody
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * @summary Train Protocol
 */
export const trainProtocolApiV1ProtocolsPost = (
    trainProtocolBody: TrainProtocolBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<RunResponse>(
      {url: `/api/v1/protocols`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: trainProtocolBody, signal
    },
      );
    }
  


export const getTrainProtocolApiV1ProtocolsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof trainProtocolApiV1ProtocolsPost>>, TError,{data: TrainProtocolBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof trainProtocolApiV1ProtocolsPost>>, TError,{data: TrainProtocolBody}, TContext> => {

const mutationKey = ['trainProtocolApiV1ProtocolsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof trainProtocolApiV1ProtocolsPost>>, {data: TrainProtocolBody}> = (props) => {
          const {data} = props ?? {};

          return  trainProtocolApiV1ProtocolsPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TrainProtocolApiV1ProtocolsPostMutationResult = NonNullable<Awaited<ReturnType<typeof trainProtocolApiV1ProtocolsPost>>>
    export type TrainProtocolApiV1ProtocolsPostMutationBody = TrainProtocolBody
    export type TrainProtocolApiV1ProtocolsPostMutationError = HTTPValidationError

    /**
 * @summary Train Protocol
 */
export const useTrainProtocolApiV1ProtocolsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof trainProtocolApiV1ProtocolsPost>>, TError,{data: TrainProtocolBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof trainProtocolApiV1ProtocolsPost>>,
        TError,
        {data: TrainProtocolBody},
        TContext
      > => {

      const mutationOptions = getTrainProtocolApiV1ProtocolsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List Protocols
 */
export const listProtocolsApiV1ProtocolsGet = (
    params?: ListProtocolsApiV1ProtocolsGetParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PaginatedResponseProtocolResponse>(
      {url: `/api/v1/protocols`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListProtocolsApiV1ProtocolsGetQueryKey = (params?: ListProtocolsApiV1ProtocolsGetParams,) => {
    return [
    `/api/v1/protocols`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListProtocolsApiV1ProtocolsGetQueryOptions = <TData = Awaited<ReturnType<typeof listProtocolsApiV1ProtocolsGet>>, TError = HTTPValidationError>(params?: ListProtocolsApiV1ProtocolsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProtocolsApiV1ProtocolsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListProtocolsApiV1ProtocolsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listProtocolsApiV1ProtocolsGet>>> = ({ signal }) => listProtocolsApiV1ProtocolsGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listProtocolsApiV1ProtocolsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListProtocolsApiV1ProtocolsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listProtocolsApiV1ProtocolsGet>>>
export type ListProtocolsApiV1ProtocolsGetQueryError = HTTPValidationError


export function useListProtocolsApiV1ProtocolsGet<TData = Awaited<ReturnType<typeof listProtocolsApiV1ProtocolsGet>>, TError = HTTPValidationError>(
 params: undefined |  ListProtocolsApiV1ProtocolsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProtocolsApiV1ProtocolsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProtocolsApiV1ProtocolsGet>>,
          TError,
          Awaited<ReturnType<typeof listProtocolsApiV1ProtocolsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListProtocolsApiV1ProtocolsGet<TData = Awaited<ReturnType<typeof listProtocolsApiV1ProtocolsGet>>, TError = HTTPValidationError>(
 params?: ListProtocolsApiV1ProtocolsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProtocolsApiV1ProtocolsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProtocolsApiV1ProtocolsGet>>,
          TError,
          Awaited<ReturnType<typeof listProtocolsApiV1ProtocolsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListProtocolsApiV1ProtocolsGet<TData = Awaited<ReturnType<typeof listProtocolsApiV1ProtocolsGet>>, TError = HTTPValidationError>(
 params?: ListProtocolsApiV1ProtocolsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProtocolsApiV1ProtocolsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Protocols
 */

export function useListProtocolsApiV1ProtocolsGet<TData = Awaited<ReturnType<typeof listProtocolsApiV1ProtocolsGet>>, TError = HTTPValidationError>(
 params?: ListProtocolsApiV1ProtocolsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProtocolsApiV1ProtocolsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListProtocolsApiV1ProtocolsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get Protocol
 */
export const getProtocolApiV1ProtocolsProtocolIdGet = (
    protocolId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ProtocolResponse>(
      {url: `/api/v1/protocols/${protocolId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetProtocolApiV1ProtocolsProtocolIdGetQueryKey = (protocolId?: string,) => {
    return [
    `/api/v1/protocols/${protocolId}`
    ] as const;
    }

    
export const getGetProtocolApiV1ProtocolsProtocolIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getProtocolApiV1ProtocolsProtocolIdGet>>, TError = HTTPValidationError>(protocolId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProtocolApiV1ProtocolsProtocolIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProtocolApiV1ProtocolsProtocolIdGetQueryKey(protocolId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProtocolApiV1ProtocolsProtocolIdGet>>> = ({ signal }) => getProtocolApiV1ProtocolsProtocolIdGet(protocolId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(protocolId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProtocolApiV1ProtocolsProtocolIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProtocolApiV1ProtocolsProtocolIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getProtocolApiV1ProtocolsProtocolIdGet>>>
export type GetProtocolApiV1ProtocolsProtocolIdGetQueryError = HTTPValidationError


export function useGetProtocolApiV1ProtocolsProtocolIdGet<TData = Awaited<ReturnType<typeof getProtocolApiV1ProtocolsProtocolIdGet>>, TError = HTTPValidationError>(
 protocolId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProtocolApiV1ProtocolsProtocolIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProtocolApiV1ProtocolsProtocolIdGet>>,
          TError,
          Awaited<ReturnType<typeof getProtocolApiV1ProtocolsProtocolIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProtocolApiV1ProtocolsProtocolIdGet<TData = Awaited<ReturnType<typeof getProtocolApiV1ProtocolsProtocolIdGet>>, TError = HTTPValidationError>(
 protocolId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProtocolApiV1ProtocolsProtocolIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProtocolApiV1ProtocolsProtocolIdGet>>,
          TError,
          Awaited<ReturnType<typeof getProtocolApiV1ProtocolsProtocolIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProtocolApiV1ProtocolsProtocolIdGet<TData = Awaited<ReturnType<typeof getProtocolApiV1ProtocolsProtocolIdGet>>, TError = HTTPValidationError>(
 protocolId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProtocolApiV1ProtocolsProtocolIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Protocol
 */

export function useGetProtocolApiV1ProtocolsProtocolIdGet<TData = Awaited<ReturnType<typeof getProtocolApiV1ProtocolsProtocolIdGet>>, TError = HTTPValidationError>(
 protocolId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProtocolApiV1ProtocolsProtocolIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProtocolApiV1ProtocolsProtocolIdGetQueryOptions(protocolId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get Scorecard
 */
export const getScorecardApiV1ProtocolsProtocolIdScorecardGet = (
    protocolId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ScorecardResponse>(
      {url: `/api/v1/protocols/${protocolId}/scorecard`, method: 'GET', signal
    },
      );
    }
  



export const getGetScorecardApiV1ProtocolsProtocolIdScorecardGetQueryKey = (protocolId?: string,) => {
    return [
    `/api/v1/protocols/${protocolId}/scorecard`
    ] as const;
    }

    
export const getGetScorecardApiV1ProtocolsProtocolIdScorecardGetQueryOptions = <TData = Awaited<ReturnType<typeof getScorecardApiV1ProtocolsProtocolIdScorecardGet>>, TError = HTTPValidationError>(protocolId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getScorecardApiV1ProtocolsProtocolIdScorecardGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetScorecardApiV1ProtocolsProtocolIdScorecardGetQueryKey(protocolId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getScorecardApiV1ProtocolsProtocolIdScorecardGet>>> = ({ signal }) => getScorecardApiV1ProtocolsProtocolIdScorecardGet(protocolId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(protocolId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getScorecardApiV1ProtocolsProtocolIdScorecardGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetScorecardApiV1ProtocolsProtocolIdScorecardGetQueryResult = NonNullable<Awaited<ReturnType<typeof getScorecardApiV1ProtocolsProtocolIdScorecardGet>>>
export type GetScorecardApiV1ProtocolsProtocolIdScorecardGetQueryError = HTTPValidationError


export function useGetScorecardApiV1ProtocolsProtocolIdScorecardGet<TData = Awaited<ReturnType<typeof getScorecardApiV1ProtocolsProtocolIdScorecardGet>>, TError = HTTPValidationError>(
 protocolId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getScorecardApiV1ProtocolsProtocolIdScorecardGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getScorecardApiV1ProtocolsProtocolIdScorecardGet>>,
          TError,
          Awaited<ReturnType<typeof getScorecardApiV1ProtocolsProtocolIdScorecardGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetScorecardApiV1ProtocolsProtocolIdScorecardGet<TData = Awaited<ReturnType<typeof getScorecardApiV1ProtocolsProtocolIdScorecardGet>>, TError = HTTPValidationError>(
 protocolId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getScorecardApiV1ProtocolsProtocolIdScorecardGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getScorecardApiV1ProtocolsProtocolIdScorecardGet>>,
          TError,
          Awaited<ReturnType<typeof getScorecardApiV1ProtocolsProtocolIdScorecardGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetScorecardApiV1ProtocolsProtocolIdScorecardGet<TData = Awaited<ReturnType<typeof getScorecardApiV1ProtocolsProtocolIdScorecardGet>>, TError = HTTPValidationError>(
 protocolId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getScorecardApiV1ProtocolsProtocolIdScorecardGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Scorecard
 */

export function useGetScorecardApiV1ProtocolsProtocolIdScorecardGet<TData = Awaited<ReturnType<typeof getScorecardApiV1ProtocolsProtocolIdScorecardGet>>, TError = HTTPValidationError>(
 protocolId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getScorecardApiV1ProtocolsProtocolIdScorecardGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetScorecardApiV1ProtocolsProtocolIdScorecardGetQueryOptions(protocolId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Publish Protocol
 */
export const publishProtocolApiV1ProtocolsProtocolIdPublishPost = (
    protocolId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/protocols/${protocolId}/publish`, method: 'POST', signal
    },
      );
    }
  


export const getPublishProtocolApiV1ProtocolsProtocolIdPublishPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof publishProtocolApiV1ProtocolsProtocolIdPublishPost>>, TError,{protocolId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof publishProtocolApiV1ProtocolsProtocolIdPublishPost>>, TError,{protocolId: string}, TContext> => {

const mutationKey = ['publishProtocolApiV1ProtocolsProtocolIdPublishPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof publishProtocolApiV1ProtocolsProtocolIdPublishPost>>, {protocolId: string}> = (props) => {
          const {protocolId} = props ?? {};

          return  publishProtocolApiV1ProtocolsProtocolIdPublishPost(protocolId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PublishProtocolApiV1ProtocolsProtocolIdPublishPostMutationResult = NonNullable<Awaited<ReturnType<typeof publishProtocolApiV1ProtocolsProtocolIdPublishPost>>>
    
    export type PublishProtocolApiV1ProtocolsProtocolIdPublishPostMutationError = HTTPValidationError

    /**
 * @summary Publish Protocol
 */
export const usePublishProtocolApiV1ProtocolsProtocolIdPublishPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof publishProtocolApiV1ProtocolsProtocolIdPublishPost>>, TError,{protocolId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof publishProtocolApiV1ProtocolsProtocolIdPublishPost>>,
        TError,
        {protocolId: string},
        TContext
      > => {

      const mutationOptions = getPublishProtocolApiV1ProtocolsProtocolIdPublishPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    