/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

export interface ActivityCliffResponse {
  left_structure: string;
  right_structure: string;
  left_value: number;
  right_value: number;
  similarity: number;
  delta: number;
}
