/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */

export interface ActivityCliffResponse {
  left_structure: string;
  right_structure: string;
  left_value: number;
  right_value: number;
  similarity: number;
  delta: number;
}
