/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

/**
 * Bounds, how many rows fell in them, and what was measured.

Similarity bounds are the inclusive observed minimum and maximum;
calibration intervals are half-open, except the last includes 1.

`value` is mean absolute error in `error_by_similarity` and observed
positive rate in `calibration` -- the owning field says which, the same way
`prediction_kind` says what `worst_rows.residual` means.
 */
export interface BinResponse {
  lower: number;
  upper: number;
  count: number;
  value: number;
}
