/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

/**
 * A half-open interval, how many rows fell in it, and what was measured.

`value` is mean absolute error in `error_by_similarity` and observed
positive rate in `calibration` -- the owning field says which, the same way
`prediction_kind` says what `worst_rows.residual` means.
 */
export interface BinResponse {
  lower: number;
  upper: number;
  count: number;
  value: number;
}
