/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */

/**
 * `edges` is one longer than `counts`: the primary metric on each of the
interval's redraws, binned. Its own name for the same reason as
`ResidualHistogramResponse`, and so the client type says what it holds.
 */
export interface BootstrapHistogramResponse {
  edges: number[];
  counts: number[];
}
