/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

/**
 * `edges` is one longer than `counts`: the primary metric on each of the
interval's redraws, binned. Its own name for the same reason as
`ResidualHistogramResponse`, and so the client type says what it holds.
 */
export interface BootstrapHistogramResponse {
  edges: number[];
  counts: number[];
}
