/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

/**
 * Parallel arrays, one entry per dataset compound in snapshot order. `x`/`y`
are in the unit square; `partition` is 0 train, 1 validation, 2 test.
 */
export interface ChemicalSpacePointsResponse {
  x: number[];
  y: number[];
  partition: number[];
}
