/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */

/**
 * Parallel arrays, one entry per dataset compound in snapshot order. `x`/`y`
are in the unit square; `partition` is 0 train, 1 validation, 2 test.
 */
export interface ChemicalSpacePointsResponse {
  x: number[];
  y: number[];
  partition: number[];
}
