/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { ChemicalSpaceResponseStatus } from './chemicalSpaceResponseStatus';
import type { ChemicalSpaceResponseMethod } from './chemicalSpaceResponseMethod';
import type { ChemicalSpaceResponseParams } from './chemicalSpaceResponseParams';
import type { ChemicalSpaceResponseCounts } from './chemicalSpaceResponseCounts';
import type { ChemicalSpaceResponsePoints } from './chemicalSpaceResponsePoints';

/**
 * `missing` is a normal state: a protocol trained before maps existed, or a
dataset too small to map. The client shows "no map", not an error.
 */
export interface ChemicalSpaceResponse {
  status: ChemicalSpaceResponseStatus;
  method?: ChemicalSpaceResponseMethod;
  params?: ChemicalSpaceResponseParams;
  counts?: ChemicalSpaceResponseCounts;
  points?: ChemicalSpaceResponsePoints;
}
