/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { ChemicalSpaceResponseParamsAnyOf } from './chemicalSpaceResponseParamsAnyOf';

export type ChemicalSpaceResponseParams = ChemicalSpaceResponseParamsAnyOf | null;
