/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

export interface ChemCellarRunResponse {
  id: string;
  protocol_id: string;
  run_date: string;
  status: string;
  measured_count: number;
  plate_count: number;
  plate_barcodes: string[];
}
