/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { ChemicalSpaceResponseCountsAnyOf } from './chemicalSpaceResponseCountsAnyOf';

export type ChemicalSpaceResponseCounts = ChemicalSpaceResponseCountsAnyOf | null;
