/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { ChemicalSpacePointsResponse } from './chemicalSpacePointsResponse';

export type ChemicalSpaceResponsePoints = ChemicalSpacePointsResponse | null;
