/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

export type ChemicalSpaceResponseStatus = typeof ChemicalSpaceResponseStatus[keyof typeof ChemicalSpaceResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChemicalSpaceResponseStatus = {
  ready: 'ready',
  missing: 'missing',
} as const;
