/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { RunSourceResponse } from './runSourceResponse';

export interface ChemCellarImportResponse {
  upload_ref: string;
  compound_count: number;
  without_structure: number;
  sample: string[];
  source: RunSourceResponse;
}
