/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { CitationResponsePmid } from './citationResponsePmid';
import type { CitationResponseDoi } from './citationResponseDoi';
import type { CitationResponseUrl } from './citationResponseUrl';
import type { CitationResponseLabel } from './citationResponseLabel';

export interface CitationResponse {
  pmid: CitationResponsePmid;
  doi: CitationResponseDoi;
  url: CitationResponseUrl;
  label: CitationResponseLabel;
}
