/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { CitationResponsePmid } from './citationResponsePmid';
import type { CitationResponseDoi } from './citationResponseDoi';
import type { CitationResponseUrl } from './citationResponseUrl';
import type { CitationResponseLabel } from './citationResponseLabel';

export interface CitationResponse {
  pmid: CitationResponsePmid;
  doi: CitationResponseDoi;
  url: CitationResponseUrl;
  label: CitationResponseLabel;
}
