/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { RunEnvelope } from './runEnvelope';

/**
 * What a runner gets back for claiming a queued run: the run itself,
plus how long it has before the server treats the claim as abandoned.
 */
export interface ClaimResponse {
  run: RunEnvelope;
  deadline_seconds: number;
}
