/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { ClassificationSummaryResponsePrecision } from './classificationSummaryResponsePrecision';
import type { ClassificationSummaryResponseRecall } from './classificationSummaryResponseRecall';

export interface ClassificationSummaryResponse {
  true_positive: number;
  false_negative: number;
  false_positive: number;
  true_negative: number;
  precision: ClassificationSummaryResponsePrecision;
  recall: ClassificationSummaryResponseRecall;
  cutoff_inclusive: boolean;
}
