/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { ClassificationSummaryResponse } from './classificationSummaryResponse';

export interface ClassificationBinResponse {
  lower: number;
  upper: number;
  count: number;
  summary: ClassificationSummaryResponse;
}
