/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { ProvenanceResponse } from './provenanceResponse';

export interface CollectionResponse {
  id: string;
  workspace_id: string;
  name: string;
  derived_from_run_id: string;
  member_count: number;
  snapshot_uri: string;
  provenance: ProvenanceResponse;
  created_at: string;
}
