/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { ProvenanceResponse } from './provenanceResponse';

export interface CollectionResponse {
  id: string;
  workspace_id: string;
  name: string;
  derived_from_run_id: string;
  member_count: number;
  snapshot_uri: string;
  provenance: ProvenanceResponse;
  created_at: string;
}
