/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { ColumnRangeResponseMin } from './columnRangeResponseMin';
import type { ColumnRangeResponseMax } from './columnRangeResponseMax';

export interface ColumnRangeResponse {
  min: ColumnRangeResponseMin;
  max: ColumnRangeResponseMax;
}
