/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { ColumnRangeResponseMin } from './columnRangeResponseMin';
import type { ColumnRangeResponseMax } from './columnRangeResponseMax';

export interface ColumnRangeResponse {
  min: ColumnRangeResponseMin;
  max: ColumnRangeResponseMax;
}
