/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { CompoundResponse } from './compoundResponse';

/**
 * `total` is the count *after* the split filter, which is what a pager
needs; the Dataset's own `row_count` answers a different question.
 */
export interface CompoundPageResponse {
  items: CompoundResponse[];
  total: number;
}
