/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { ConditionResponseDefault } from './conditionResponseDefault';
import type { ConditionResponseMinimum } from './conditionResponseMinimum';
import type { ConditionResponseMaximum } from './conditionResponseMaximum';
import type { ConditionResponseHelp } from './conditionResponseHelp';

/**
 * A single engine condition parameter specification, carrying everything
a form needs to render without any hardcoded knowledge of the engine.
 */
export interface ConditionResponse {
  key: string;
  label: string;
  type: string;
  required: boolean;
  default: ConditionResponseDefault;
  minimum: ConditionResponseMinimum;
  maximum: ConditionResponseMaximum;
  options: string[];
  option_labels: string[];
  help: ConditionResponseHelp;
  tasks: string[];
}
