/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { ConflictRowResponseValues } from './conflictRowResponseValues';

export interface ConflictRowResponse {
  structure: string;
  column: string;
  values: ConflictRowResponseValues;
  row_numbers: number[];
}
