/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */

export interface ConflictRowResponse {
  structure: string;
  values: number[];
  row_numbers: number[];
}
