/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { ConflictRowValues } from './conflictRowValues';

export interface ConflictRow {
  structure: string;
  column: string;
  values: ConflictRowValues;
  row_numbers: number[];
}
