/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */

export interface CreatedRunnerResponse {
  id: string;
  name: string;
  lanes: string[];
  token: string;
  created_at: string;
}
