/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { PageOwnerKind } from './pageOwnerKind';

export interface CreatePageBody {
  title: string;
  owner_kind: PageOwnerKind;
  owner_id: string;
}
