/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */

export interface CreateCollectionBody {
  /** @maxLength 256 */
  name: string;
  run_id: string;
  row_ids: number[];
}
