/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

export interface CreatedRunnerResponse {
  id: string;
  name: string;
  lanes: string[];
  token: string;
  created_at: string;
}
