/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { TargetBody } from './targetBody';
import type { SplitBody } from './splitBody';
import type { CreateDatasetBodyIdColumn } from './createDatasetBodyIdColumn';
import type { CreateDatasetBodyFileName } from './createDatasetBodyFileName';

export interface CreateDatasetBody {
  /** @maxLength 256 */
  name: string;
  upload_ref: string;
  /** @maxLength 128 */
  structure_column: string;
  /** @minItems 1 */
  targets: TargetBody[];
  split: SplitBody;
  id_column?: CreateDatasetBodyIdColumn;
  file_name?: CreateDatasetBodyFileName;
  deduplicate?: boolean;
}
