/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { TargetBody } from './targetBody';
import type { SplitBody } from './splitBody';

export interface CreateDatasetBody {
  /** @maxLength 256 */
  name: string;
  upload_ref: string;
  /** @maxLength 128 */
  structure_column: string;
  target: TargetBody;
  split: SplitBody;
}
