/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { DatasetBuildResponseErrorAnyOf } from './datasetBuildResponseErrorAnyOf';

export type DatasetBuildResponseError = DatasetBuildResponseErrorAnyOf | null;
