/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { DatasetPreparationResponse } from './datasetPreparationResponse';

export type DatasetPreviewResponsePreparation = DatasetPreparationResponse | null;
