/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */

/**
 * Snapshot columns that may be named as the identifier.
 */
export interface DatasetColumnsResponse {
  columns: string[];
}
