/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { VariantProfileResponse } from './variantProfileResponse';

export type DatasetProfileResponseVariants = VariantProfileResponse | null;
