/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { DatasetProfileResponsePartitionCounts } from './datasetProfileResponsePartitionCounts';
import type { DatasetProfileResponseTargetDistribution } from './datasetProfileResponseTargetDistribution';
import type { ClassBalanceResponse } from './classBalanceResponse';
import type { DatasetProfileResponseSimilarity } from './datasetProfileResponseSimilarity';
import type { ScaffoldProfileResponse } from './scaffoldProfileResponse';
import type { DescriptorProfileResponse } from './descriptorProfileResponse';
import type { DatasetProfileResponseBestDescriptor } from './datasetProfileResponseBestDescriptor';
import type { ActivityCliffResponse } from './activityCliffResponse';
import type { DatasetProfileResponseCliffsSampledFrom } from './datasetProfileResponseCliffsSampledFrom';

/**
 * What the Dataset is made of -- see `domain/data/profile.py` for what each
section means and why it is here.

`target_distribution` and `class_balance` are mutually exclusive: a numeric
target populates the first and a binary one the second, so a consumer must
branch on `target_kind` rather than render whichever is non-empty.

`similarity` is `null` only when there was no train/test pair to compare,
never an all-zero histogram. `cliffs_sampled_from` is non-null when the
pair scan ran on a subsample -- "no cliffs found among 3000 of 12000
compounds" is a different claim from "no cliffs", and this is which one
was made.
 */
export interface DatasetProfileResponse {
  compounds: number;
  partition_counts: DatasetProfileResponsePartitionCounts;
  target_kind: string;
  target_distribution: DatasetProfileResponseTargetDistribution;
  class_balance: ClassBalanceResponse[];
  similarity: DatasetProfileResponseSimilarity;
  scaffolds: ScaffoldProfileResponse;
  descriptors: DescriptorProfileResponse[];
  best_descriptor: DatasetProfileResponseBestDescriptor;
  activity_cliffs: ActivityCliffResponse[];
  cliffs_sampled_from: DatasetProfileResponseCliffsSampledFrom;
}
