/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

export type DatasetBuildResponseStatus = typeof DatasetBuildResponseStatus[keyof typeof DatasetBuildResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DatasetBuildResponseStatus = {
  running: 'running',
  succeeded: 'succeeded',
  failed: 'failed',
} as const;
