/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { TargetDistributionResponse } from './targetDistributionResponse';

export type DatasetProfileResponseTargetDistribution = TargetDistributionResponse | null;
