/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { DatasetPreparationResponseFileName } from './datasetPreparationResponseFileName';
import type { TargetBody } from './targetBody';
import type { SplitBody } from './splitBody';
import type { DatasetPreparationResponseIdColumn } from './datasetPreparationResponseIdColumn';
import type { ValidationReportResponse } from './validationReportResponse';
import type { DatasetReadinessResponse } from './datasetReadinessResponse';

export interface DatasetPreparationResponse {
  name: string;
  file_name?: DatasetPreparationResponseFileName;
  structure_column: string;
  targets: TargetBody[];
  split: SplitBody;
  id_column: DatasetPreparationResponseIdColumn;
  validation_report: ValidationReportResponse;
  readiness: DatasetReadinessResponse;
  expires_at: string;
}
