/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { ScaffoldProfileResponse } from './scaffoldProfileResponse';

export type DatasetProfileResponseScaffolds = ScaffoldProfileResponse | null;
