/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { TargetBody } from './targetBody';
import type { SplitBody } from './splitBody';
import type { ValidationReportResponse } from './validationReportResponse';
import type { DatasetResponseIdColumn } from './datasetResponseIdColumn';
import type { DatasetResponseCreatedBy } from './datasetResponseCreatedBy';
import type { DatasetResponseFolderId } from './datasetResponseFolderId';

export interface DatasetResponse {
  id: string;
  workspace_id: string;
  name: string;
  structure_column: string;
  targets: TargetBody[];
  split: SplitBody;
  content_hash: string;
  snapshot_uri: string;
  row_count: number;
  validation_report: ValidationReportResponse;
  version: number;
  created_at: string;
  can_delete: boolean;
  id_column: DatasetResponseIdColumn;
  can_edit: boolean;
  created_by: DatasetResponseCreatedBy;
  folder_id: DatasetResponseFolderId;
}
