/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

export type DatasetPreviewResponseStatus = typeof DatasetPreviewResponseStatus[keyof typeof DatasetPreviewResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DatasetPreviewResponseStatus = {
  running: 'running',
  succeeded: 'succeeded',
  failed: 'failed',
} as const;
