/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { DatasetBuildResponseStatus } from './datasetBuildResponseStatus';
import type { DatasetBuildResponseDatasetId } from './datasetBuildResponseDatasetId';
import type { DatasetBuildResponseError } from './datasetBuildResponseError';

/**
 * A dataset being built. `done` of `total` rows through `stage`; `total` is 0 for a
stage with no row count. On `failed`, `error` is the body `POST /datasets` would
have answered with (a 422's `detail` is the whole validation report).
 */
export interface DatasetBuildResponse {
  id: string;
  name: string;
  status: DatasetBuildResponseStatus;
  stage: string;
  done: number;
  total: number;
  dataset_id: DatasetBuildResponseDatasetId;
  error: DatasetBuildResponseError;
  created_at: string;
  updated_at: string;
}
