/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { DatasetPreviewResponseErrorAnyOf } from './datasetPreviewResponseErrorAnyOf';

export type DatasetPreviewResponseError = DatasetPreviewResponseErrorAnyOf | null;
