/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

/**
 * Snapshot columns that may be named as the identifier.
 */
export interface DatasetColumnsResponse {
  columns: string[];
}
