/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { SimilarityProfileResponse } from './similarityProfileResponse';

export type DatasetProfileResponseSimilarity = SimilarityProfileResponse | null;
