/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { TargetSpecWire } from './targetSpecWire';
import type { SplitSpecWire } from './splitSpecWire';
import type { ValidationReportWire } from './validationReportWire';

/**
 * Mirrors every `Dataset.__init__` kwarg (`domain/data/dataset.py`).
 */
export interface DatasetEnvelope {
  id: string;
  workspace_id: string;
  name: string;
  structure_column: string;
  targets: TargetSpecWire[];
  split: SplitSpecWire;
  content_hash: string;
  snapshot_uri: string;
  row_count: number;
  validation_report: ValidationReportWire;
  created_at: string;
  updated_at: string;
  version: number;
}
