/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { SplitHistogramResponse } from './splitHistogramResponse';
import type { DescriptorProfileResponseTargetCorrelation } from './descriptorProfileResponseTargetCorrelation';

export interface DescriptorProfileResponse {
  name: string;
  histogram: SplitHistogramResponse;
  median: number;
  target_correlation: DescriptorProfileResponseTargetCorrelation;
}
