/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { SplitHistogramResponse } from './splitHistogramResponse';
import type { DescriptorProfileResponseTargetCorrelation } from './descriptorProfileResponseTargetCorrelation';

export interface DescriptorProfileResponse {
  name: string;
  histogram: SplitHistogramResponse;
  median: number;
  target_correlation: DescriptorProfileResponseTargetCorrelation;
}
