/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

export type Direction = typeof Direction[keyof typeof Direction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Direction = {
  high: 'high',
  low: 'low',
} as const;
