/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */

export type Direction = typeof Direction[keyof typeof Direction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Direction = {
  high: 'high',
  low: 'low',
} as const;
