/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { ConditionResponse } from './conditionResponse';

/**
 * An engine's manifest: its identity, capabilities, and parameter specifications.
 */
export interface EngineManifestResponse {
  id: string;
  version: string;
  name: string;
  description: string;
  tasks: string[];
  conditions: ConditionResponse[];
  is_baseline: boolean;
}
