/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { ConditionResponse } from './conditionResponse';

/**
 * An engine's manifest: its identity, capabilities, and parameter specifications.
 */
export interface EngineManifestResponse {
  id: string;
  version: string;
  name: string;
  description: string;
  tasks: string[];
  conditions: ConditionResponse[];
  is_baseline: boolean;
  supports_multitask: boolean;
  lane: string;
}
