/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { EpochWireTrainLoss } from './epochWireTrainLoss';
import type { EpochWireValLoss } from './epochWireValLoss';
import type { EpochWireScores } from './epochWireScores';
import type { EpochWireDevice } from './epochWireDevice';
import type { EpochWireMember } from './epochWireMember';
import type { EpochWireMembers } from './epochWireMembers';
import type { EpochWireTarget } from './epochWireTarget';
import type { EpochWireKeptEpoch } from './epochWireKeptEpoch';
import type { EpochWireKeptBy } from './epochWireKeptBy';

/**
 * One finished training epoch, runner to API (application.engines.context.EpochPoint).

Bounded field by field, like everything else a self-hosted runner writes: the
rows land in the API's database and are drawn on a scientist's screen.
 */
export interface EpochWire {
  /**
   * @minimum 1
   * @maximum 100000
   */
  epoch: number;
  /**
   * @minimum 1
   * @maximum 100000
   */
  epochs: number;
  train_loss?: EpochWireTrainLoss;
  val_loss?: EpochWireValLoss;
  scores: EpochWireScores;
  device?: EpochWireDevice;
  member?: EpochWireMember;
  members?: EpochWireMembers;
  target?: EpochWireTarget;
  /** @maxLength 32 */
  fit: string;
  kept_epoch?: EpochWireKeptEpoch;
  kept_by?: EpochWireKeptBy;
  at: string;
}
