/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { EpochResponseTarget } from './epochResponseTarget';
import type { EpochResponseMember } from './epochResponseMember';
import type { EpochResponseMembers } from './epochResponseMembers';
import type { EpochResponseTrainLoss } from './epochResponseTrainLoss';
import type { EpochResponseValLoss } from './epochResponseValLoss';
import type { EpochResponseScores } from './epochResponseScores';
import type { EpochResponseDevice } from './epochResponseDevice';

/**
 * One finished epoch of a neural fit. `fit` is the training run's stage (model,
baseline, random-split); `target` is None for one fit over every target at once;
`scores` are validation scores in the shared vocabulary.
 */
export interface EpochResponse {
  fit: string;
  target: EpochResponseTarget;
  member: EpochResponseMember;
  members: EpochResponseMembers;
  epoch: number;
  epochs: number;
  train_loss: EpochResponseTrainLoss;
  val_loss: EpochResponseValLoss;
  scores: EpochResponseScores;
  device: EpochResponseDevice;
  at: string;
}
