/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { EpochWire } from './epochWire';

/**
 * What a runner posts at each progress write: the epochs finished since the last.
 */
export interface EpochBatchWire {
  /** @maxItems 1000 */
  points: EpochWire[];
}
