/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */

export type ExportRunResultsApiV1RunsRunIdResultsExportGetSortDir = typeof ExportRunResultsApiV1RunsRunIdResultsExportGetSortDir[keyof typeof ExportRunResultsApiV1RunsRunIdResultsExportGetSortDir];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExportRunResultsApiV1RunsRunIdResultsExportGetSortDir = {
  asc: 'asc',
  desc: 'desc',
} as const;
