/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */

export type ExportFormat = typeof ExportFormat[keyof typeof ExportFormat];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExportFormat = {
  csv: 'csv',
  sdf: 'sdf',
} as const;
