/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { ExportRunResultsApiV1RunsRunIdResultsExportGetSortDir } from './exportRunResultsApiV1RunsRunIdResultsExportGetSortDir';

export type ExportRunResultsApiV1RunsRunIdResultsExportGetParams = {
sort_by?: string | null;
sort_dir?: ExportRunResultsApiV1RunsRunIdResultsExportGetSortDir;
filters?: string | null;
};
