/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { ExportFormat } from './exportFormat';

export type ExportCollectionApiV1CollectionsCollectionIdExportGetParams = {
format: ExportFormat;
};
