/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

export type ExportFormat = typeof ExportFormat[keyof typeof ExportFormat];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExportFormat = {
  csv: 'csv',
  sdf: 'sdf',
} as const;
