/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

export type ExportRunResultsApiV1RunsRunIdResultsExportGetSortDir = typeof ExportRunResultsApiV1RunsRunIdResultsExportGetSortDir[keyof typeof ExportRunResultsApiV1RunsRunIdResultsExportGetSortDir];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExportRunResultsApiV1RunsRunIdResultsExportGetSortDir = {
  asc: 'asc',
  desc: 'desc',
} as const;
