/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { ExportRunResultsApiV1RunsRunIdResultsExportGetSortDir } from './exportRunResultsApiV1RunsRunIdResultsExportGetSortDir';

export type ExportRunResultsApiV1RunsRunIdResultsExportGetParams = {
sort_by?: string | null;
sort_dir?: ExportRunResultsApiV1RunsRunIdResultsExportGetSortDir;
filters?: string | null;
};
