/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { ExportFormat } from './exportFormat';

export type ExportCollectionApiV1CollectionsCollectionIdExportGetParams = {
format: ExportFormat;
};
