/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { FolderKind } from './folderKind';

export interface FolderResponse {
  id: string;
  kind: FolderKind;
  name: string;
  item_count: number;
  created_by: string;
}
