/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

export type FolderKind = typeof FolderKind[keyof typeof FolderKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FolderKind = {
  dataset: 'dataset',
  protocol: 'protocol',
} as const;
