/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { FolderBodyFolderId } from './folderBodyFolderId';

export interface FolderBody {
  folder_id: FolderBodyFolderId;
}
