/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { FolderResponse } from './folderResponse';

export interface FolderListResponse {
  items: FolderResponse[];
  can_edit: boolean;
}
