/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

export type GetChemicalSpaceCompoundsApiV1ProtocolsProtocolIdChemicalSpaceCompoundsGetParams = {
/**
 * @maxItems 50
 */
indices: number[];
};
