/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { GetDatasetCompoundsApiV1DatasetsDatasetIdCompoundsGetSortDir } from './getDatasetCompoundsApiV1DatasetsDatasetIdCompoundsGetSortDir';

export type GetDatasetCompoundsApiV1DatasetsDatasetIdCompoundsGetParams = {
offset?: number;
limit?: number;
sort?: 'target' | 'split' | null;
/**
 * @minimum 0
 */
target?: number;
sort_dir?: GetDatasetCompoundsApiV1DatasetsDatasetIdCompoundsGetSortDir;
split?: 'train' | 'validation' | 'test' | null;
q?: string | null;
};
