/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

export type GetDatasetCompoundsApiV1DatasetsDatasetIdCompoundsGetSortDir = typeof GetDatasetCompoundsApiV1DatasetsDatasetIdCompoundsGetSortDir[keyof typeof GetDatasetCompoundsApiV1DatasetsDatasetIdCompoundsGetSortDir];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetDatasetCompoundsApiV1DatasetsDatasetIdCompoundsGetSortDir = {
  asc: 'asc',
  desc: 'desc',
} as const;
