/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */

export type GetDatasetCompoundsApiV1DatasetsDatasetIdCompoundsGetSortDir = typeof GetDatasetCompoundsApiV1DatasetsDatasetIdCompoundsGetSortDir[keyof typeof GetDatasetCompoundsApiV1DatasetsDatasetIdCompoundsGetSortDir];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetDatasetCompoundsApiV1DatasetsDatasetIdCompoundsGetSortDir = {
  asc: 'asc',
  desc: 'desc',
} as const;
