/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */

export type GetRunResultsApiV1RunsRunIdResultsGetSortDir = typeof GetRunResultsApiV1RunsRunIdResultsGetSortDir[keyof typeof GetRunResultsApiV1RunsRunIdResultsGetSortDir];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRunResultsApiV1RunsRunIdResultsGetSortDir = {
  asc: 'asc',
  desc: 'desc',
} as const;
