/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

export type GetRunResultsApiV1RunsRunIdResultsGetSortDir = typeof GetRunResultsApiV1RunsRunIdResultsGetSortDir[keyof typeof GetRunResultsApiV1RunsRunIdResultsGetSortDir];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRunResultsApiV1RunsRunIdResultsGetSortDir = {
  asc: 'asc',
  desc: 'desc',
} as const;
