/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

export type GetRunChemicalSpaceCompoundsApiV1RunsRunIdChemicalSpaceCompoundsGetParams = {
/**
 * @maxItems 50
 */
rows: number[];
};
