/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { ColumnRangeResponse } from './columnRangeResponse';

export type GetRunResultRangesApiV1RunsRunIdResultsRangesGet200 = {[key: string]: ColumnRangeResponse};
