/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { GetRunResultsApiV1RunsRunIdResultsGetSortDir } from './getRunResultsApiV1RunsRunIdResultsGetSortDir';

export type GetRunResultsApiV1RunsRunIdResultsGetParams = {
cursor?: string | null;
limit?: number | null;
sort_by?: string | null;
sort_dir?: GetRunResultsApiV1RunsRunIdResultsGetSortDir;
filters?: string | null;
};
