/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

export type GetScorecardToleranceApiV1ProtocolsProtocolIdScorecardToleranceGetParams = {
/**
 * @minLength 1
 */
target: string;
/**
 * @minimum 0
 */
tolerance: number;
};
