/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */

/**
 * `edges` is one longer than `counts`; bin *i* spans `edges[i]`..`edges[i+1]`.
 */
export interface HistogramResponse {
  edges: number[];
  counts: number[];
}
