/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

/**
 * `edges` is one longer than `counts`; bin *i* spans `edges[i]`..`edges[i+1]`.
 */
export interface HistogramResponse {
  edges: number[];
  counts: number[];
}
