/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { ValidationError } from './validationError';

export interface HTTPValidationError {
  detail?: ValidationError[];
}
