/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */

export interface InvalidRow {
  row_number: number;
  value: string;
  reason: string;
}
