/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { ProtocolStatus } from './protocolStatus';

export type ListProtocolsApiV1ProtocolsGetParams = {
cursor?: string | null;
limit?: number | null;
dataset_id?: string | null;
mine?: boolean;
folder_id?: string | null;
q?: string | null;
engine_id?: string | null;
status?: ProtocolStatus | null;
};
