/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { PageOwnerKind } from './pageOwnerKind';

export type ListPagesApiV1PagesGetParams = {
owner_kind: PageOwnerKind;
owner_id: string;
archived?: boolean;
};
