/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { RunKind } from './runKind';

export type ListRunsApiV1RunsGetParams = {
kind?: RunKind | null;
protocol_id?: string | null;
cursor?: string | null;
limit?: number | null;
};
