/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { TargetKind } from './targetKind';
import type { SplitStrategy } from './splitStrategy';

export type ListDatasetsApiV1DatasetsGetParams = {
cursor?: string | null;
limit?: number | null;
folder_id?: string | null;
q?: string | null;
target_kind?: TargetKind | null;
split_strategy?: SplitStrategy | null;
};
