/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { MapCompoundResponsePartition } from './mapCompoundResponsePartition';
import type { MapCompoundResponseCompoundId } from './mapCompoundResponseCompoundId';

export interface MapCompoundResponse {
  index: number;
  structure: string;
  partition: MapCompoundResponsePartition;
  compound_id: MapCompoundResponseCompoundId;
}
