/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

export type MapCompoundResponsePartition = typeof MapCompoundResponsePartition[keyof typeof MapCompoundResponsePartition];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MapCompoundResponsePartition = {
  train: 'train',
  validation: 'validation',
  test: 'test',
} as const;
