/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

export interface NumericSummaryResponse {
  minimum: number;
  maximum: number;
  mean: number;
  median: number;
  std: number;
}
