/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

export type PageOwnerKind = typeof PageOwnerKind[keyof typeof PageOwnerKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PageOwnerKind = {
  dataset: 'dataset',
  protocol: 'protocol',
  run: 'run',
} as const;
