/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { PageOwnerKind } from './pageOwnerKind';
import type { PageResponseHeadSha256 } from './pageResponseHeadSha256';
import type { PageResponseLastEditedBy } from './pageResponseLastEditedBy';

export interface PageResponse {
  id: string;
  owner_kind: PageOwnerKind;
  owner_id: string;
  title: string;
  head_sha256: PageResponseHeadSha256;
  author_id: string;
  archived: boolean;
  revision_count: number;
  version: number;
  created_at: string;
  updated_at: string;
  last_edited_by: PageResponseLastEditedBy;
  can_edit: boolean;
  can_archive: boolean;
  can_delete: boolean;
}
