/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { PredictionResponse } from './predictionResponse';
import type { PaginatedResponsePredictionResponseNextCursor } from './paginatedResponsePredictionResponseNextCursor';
import type { PaginatedResponsePredictionResponseTotalCount } from './paginatedResponsePredictionResponseTotalCount';

export interface PaginatedResponsePredictionResponse {
  items: PredictionResponse[];
  next_cursor?: PaginatedResponsePredictionResponseNextCursor;
  total_count?: PaginatedResponsePredictionResponseTotalCount;
}
