/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { DatasetResponse } from './datasetResponse';
import type { PaginatedResponseDatasetResponseNextCursor } from './paginatedResponseDatasetResponseNextCursor';
import type { PaginatedResponseDatasetResponseTotalCount } from './paginatedResponseDatasetResponseTotalCount';

export interface PaginatedResponseDatasetResponse {
  items: DatasetResponse[];
  next_cursor?: PaginatedResponseDatasetResponseNextCursor;
  total_count?: PaginatedResponseDatasetResponseTotalCount;
}
