/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { CollectionResponse } from './collectionResponse';
import type { PaginatedResponseCollectionResponseNextCursor } from './paginatedResponseCollectionResponseNextCursor';
import type { PaginatedResponseCollectionResponseTotalCount } from './paginatedResponseCollectionResponseTotalCount';

export interface PaginatedResponseCollectionResponse {
  items: CollectionResponse[];
  next_cursor?: PaginatedResponseCollectionResponseNextCursor;
  total_count?: PaginatedResponseCollectionResponseTotalCount;
}
