/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { CollectionResponse } from './collectionResponse';
import type { PaginatedResponseCollectionResponseNextCursor } from './paginatedResponseCollectionResponseNextCursor';
import type { PaginatedResponseCollectionResponseTotalCount } from './paginatedResponseCollectionResponseTotalCount';

export interface PaginatedResponseCollectionResponse {
  items: CollectionResponse[];
  next_cursor?: PaginatedResponseCollectionResponseNextCursor;
  total_count?: PaginatedResponseCollectionResponseTotalCount;
}
