/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { ProtocolResponse } from './protocolResponse';
import type { PaginatedResponseProtocolResponseNextCursor } from './paginatedResponseProtocolResponseNextCursor';
import type { PaginatedResponseProtocolResponseTotalCount } from './paginatedResponseProtocolResponseTotalCount';

export interface PaginatedResponseProtocolResponse {
  items: ProtocolResponse[];
  next_cursor?: PaginatedResponseProtocolResponseNextCursor;
  total_count?: PaginatedResponseProtocolResponseTotalCount;
}
