/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { RunResponse } from './runResponse';
import type { PaginatedResponseRunResponseNextCursor } from './paginatedResponseRunResponseNextCursor';
import type { PaginatedResponseRunResponseTotalCount } from './paginatedResponseRunResponseTotalCount';

export interface PaginatedResponseRunResponse {
  items: RunResponse[];
  next_cursor?: PaginatedResponseRunResponseNextCursor;
  total_count?: PaginatedResponseRunResponseTotalCount;
}
