/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { PredictionResponse } from './predictionResponse';
import type { PaginatedResponsePredictionResponseNextCursor } from './paginatedResponsePredictionResponseNextCursor';
import type { PaginatedResponsePredictionResponseTotalCount } from './paginatedResponsePredictionResponseTotalCount';

export interface PaginatedResponsePredictionResponse {
  items: PredictionResponse[];
  next_cursor?: PaginatedResponsePredictionResponseNextCursor;
  total_count?: PaginatedResponsePredictionResponseTotalCount;
}
