/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { DatasetResponse } from './datasetResponse';
import type { PaginatedResponseDatasetResponseNextCursor } from './paginatedResponseDatasetResponseNextCursor';
import type { PaginatedResponseDatasetResponseTotalCount } from './paginatedResponseDatasetResponseTotalCount';

export interface PaginatedResponseDatasetResponse {
  items: DatasetResponse[];
  next_cursor?: PaginatedResponseDatasetResponseNextCursor;
  total_count?: PaginatedResponseDatasetResponseTotalCount;
}
