/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { RunResponse } from './runResponse';
import type { PaginatedResponseRunResponseNextCursor } from './paginatedResponseRunResponseNextCursor';
import type { PaginatedResponseRunResponseTotalCount } from './paginatedResponseRunResponseTotalCount';

export interface PaginatedResponseRunResponse {
  items: RunResponse[];
  next_cursor?: PaginatedResponseRunResponseNextCursor;
  total_count?: PaginatedResponseRunResponseTotalCount;
}
