/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { ProtocolResponse } from './protocolResponse';
import type { PaginatedResponseProtocolResponseNextCursor } from './paginatedResponseProtocolResponseNextCursor';
import type { PaginatedResponseProtocolResponseTotalCount } from './paginatedResponseProtocolResponseTotalCount';

export interface PaginatedResponseProtocolResponse {
  items: ProtocolResponse[];
  next_cursor?: PaginatedResponseProtocolResponseNextCursor;
  total_count?: PaginatedResponseProtocolResponseTotalCount;
}
