/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { ParityPointResponseSimilarity } from './parityPointResponseSimilarity';

export interface ParityPointResponse {
  actual: number;
  predicted: number;
  similarity: ParityPointResponseSimilarity;
}
