/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { PredictedReadoutResponse } from './predictedReadoutResponse';

export type PredictionResponseReadouts = {[key: string]: PredictedReadoutResponse};
