/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

/**
 * The other shape `runs.metrics` takes: `Run.record_prediction_counts` on a
prediction run. Same reasoning as `RunMetricsWire` -- two closed shapes, so
a runner still cannot store arbitrary JSON through this endpoint.
 */
export interface PredictionCountsWire {
  uploaded_rows: number;
  scored_rows: number;
}
