/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { PredictedReadoutResponseUnit } from './predictedReadoutResponseUnit';
import type { PredictedReadoutResponseDirection } from './predictedReadoutResponseDirection';

export interface PredictedReadoutResponse {
  value: number;
  unit: PredictedReadoutResponseUnit;
  direction: PredictedReadoutResponseDirection;
}
