/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { PredictedReadoutResponseUnit } from './predictedReadoutResponseUnit';
import type { PredictedReadoutResponseDirection } from './predictedReadoutResponseDirection';

export interface PredictedReadoutResponse {
  value: number;
  unit: PredictedReadoutResponseUnit;
  direction: PredictedReadoutResponseDirection;
}
