/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { PredictionResponseReadouts } from './predictionResponseReadouts';
import type { PredictionResponseUncertainty } from './predictionResponseUncertainty';
import type { PredictionResponseApplicability } from './predictionResponseApplicability';
import type { PredictionResponseInputRow } from './predictionResponseInputRow';
import type { PredictionResponseCompoundId } from './predictionResponseCompoundId';

/**
 * One scored compound. `readouts` holds one entry per Readout the
Protocol declares (a numeric value for regression; probability and class
for classification), each carrying its own unit and direction so a
prediction can be lined up against a measurement without a second call --
see `PredictionRow`'s own docstring for why `uncertainty` and
`applicability` are shaped the way they are. `uncertainty` has one entry per
target, keyed by its column.
 */
export interface PredictionResponse {
  row_id: number;
  structure: string;
  readouts: PredictionResponseReadouts;
  uncertainty: PredictionResponseUncertainty;
  applicability: PredictionResponseApplicability;
  input_row: PredictionResponseInputRow;
  compound_id: PredictionResponseCompoundId;
}
