/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { PredictBodyConditions } from './predictBodyConditions';

export interface PredictBody {
  protocol_id: string;
  upload_ref: string;
  structure_column: string;
  conditions?: PredictBodyConditions;
}
