/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { PredictBodyConditions } from './predictBodyConditions';
import type { PredictBodyIdColumn } from './predictBodyIdColumn';
import type { PredictBodyName } from './predictBodyName';

export interface PredictBody {
  protocol_id: string;
  upload_ref: string;
  structure_column: string;
  conditions?: PredictBodyConditions;
  id_column?: PredictBodyIdColumn;
  name?: PredictBodyName;
}
