/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { PredictionResponseReadouts } from './predictionResponseReadouts';
import type { PredictionResponseUncertainty } from './predictionResponseUncertainty';
import type { PredictionResponseApplicability } from './predictionResponseApplicability';

/**
 * One scored compound. `readouts` holds one entry per Readout the
Protocol declares (a numeric value for regression; probability and class
for classification), each carrying its own unit and direction so a
prediction can be lined up against a measurement without a second call --
see `PredictionRow`'s own docstring for why `uncertainty` and
`applicability` are shaped the way they are.
 */
export interface PredictionResponse {
  structure: string;
  readouts: PredictionResponseReadouts;
  uncertainty: PredictionResponseUncertainty;
  applicability: PredictionResponseApplicability;
}
