/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { PredictedReadoutResponse } from './predictedReadoutResponse';

export type PredictionResponseReadouts = {[key: string]: PredictedReadoutResponse};
