/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

/**
 * 202 while the profile is computed in the background. Poll the same URL;
every request joins the one computation, so polling never starts another.
 */
export interface ProfileComputingResponse {
  status?: 'computing';
  started_at: string;
  compounds: number;
}
