/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */

/**
 * 202 while the profile is computed in the background. Poll the same URL;
every request joins the one computation, so polling never starts another.
 */
export interface ProfileComputingResponse {
  status?: 'computing';
  started_at: string;
  compounds: number;
}
