/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

export type ProtocolStatus = typeof ProtocolStatus[keyof typeof ProtocolStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProtocolStatus = {
  draft: 'draft',
  published: 'published',
} as const;
