/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { ReadoutWire } from './readoutWire';
import type { ProtocolEnvelopeConditions } from './protocolEnvelopeConditions';
import type { ProtocolEnvelopePublishedAt } from './protocolEnvelopePublishedAt';
import type { ProtocolEnvelopeParentProtocolId } from './protocolEnvelopeParentProtocolId';

/**
 * Mirrors every `InSilicoProtocol.__init__` kwarg
(`domain/catalog/protocol.py`).
 */
export interface ProtocolEnvelope {
  id: string;
  workspace_id: string;
  name: string;
  dataset_id: string;
  engine_id: string;
  artifact_uri: string;
  readouts: ReadoutWire[];
  conditions: ProtocolEnvelopeConditions;
  status: string;
  published_at: ProtocolEnvelopePublishedAt;
  parent_protocol_id: ProtocolEnvelopeParentProtocolId;
  protocol_version: number;
  created_at: string;
  updated_at: string;
  version: number;
}
