/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { ReadoutResponse } from './readoutResponse';
import type { ProtocolResponseConditions } from './protocolResponseConditions';
import type { ProtocolResponsePublishedAt } from './protocolResponsePublishedAt';
import type { ProtocolResponseParentProtocolId } from './protocolResponseParentProtocolId';

export interface ProtocolResponse {
  id: string;
  workspace_id: string;
  name: string;
  dataset_id: string;
  engine_id: string;
  artifact_uri: string;
  readouts: ReadoutResponse[];
  conditions: ProtocolResponseConditions;
  status: string;
  is_locked: boolean;
  published_at: ProtocolResponsePublishedAt;
  parent_protocol_id: ProtocolResponseParentProtocolId;
  protocol_version: number;
  created_at: string;
  can_delete: boolean;
}
