/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { CitationResponse } from './citationResponse';
import type { ProvenanceResponseContributorResearcher } from './provenanceResponseContributorResearcher';
import type { ProvenanceResponseContributorOrganizationId } from './provenanceResponseContributorOrganizationId';
import type { ProvenanceResponseObservedOn } from './provenanceResponseObservedOn';
import type { ProvenanceResponseNote } from './provenanceResponseNote';

export interface ProvenanceResponse {
  source_type: string;
  generation_method: string;
  citations: CitationResponse[];
  contributor_researcher: ProvenanceResponseContributorResearcher;
  contributor_organization_id: ProvenanceResponseContributorOrganizationId;
  observed_on: ProvenanceResponseObservedOn;
  note: ProvenanceResponseNote;
}
