/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { RankedPredictionResponseSimilarity } from './rankedPredictionResponseSimilarity';
import type { RankedPredictionResponseCompoundId } from './rankedPredictionResponseCompoundId';

export interface RankedPredictionResponse {
  test_index: number;
  structure: string;
  actual: number;
  predicted: number;
  similarity: RankedPredictionResponseSimilarity;
  compound_id: RankedPredictionResponseCompoundId;
}
