/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */

export type ReadoutType = typeof ReadoutType[keyof typeof ReadoutType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReadoutType = {
  numeric: 'numeric',
  probability: 'probability',
  class: 'class',
} as const;
