/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { ReadoutType } from './readoutType';
import type { ReadoutResponseUnit } from './readoutResponseUnit';
import type { ReadoutResponseDirection } from './readoutResponseDirection';
import type { ReadoutResponseThreshold } from './readoutResponseThreshold';

/**
 * One declared output of a trained Protocol.

Typed rather than a bare `dict` because `unit` and `direction` are the
whole point of a Readout: they are what let a predicted IC50 be lined up
against a measured one instead of being a bare float. That pairing was
dropped at four separate boundaries during the backend build; handing the
client `dict[str, Any]` here would have invited a fifth.

`direction` is narrowed to the `Direction` enum even though `Readout` types
it as `str`. Every value `derive_readouts` can produce is a `Direction`
member or `None`, so the narrower contract is honest and gives a client a
closed union instead of an open string.
 */
export interface ReadoutResponse {
  name: string;
  type: ReadoutType;
  unit: ReadoutResponseUnit;
  direction: ReadoutResponseDirection;
  description: string;
  threshold: ReadoutResponseThreshold;
}
