/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { ReadoutWireUnit } from './readoutWireUnit';
import type { ReadoutWireDirection } from './readoutWireDirection';
import type { ReadoutWireThreshold } from './readoutWireThreshold';

/**
 * Mirrors `Readout` (`domain/catalog/readout.py`).
 */
export interface ReadoutWire {
  name: string;
  type: string;
  unit: ReadoutWireUnit;
  direction: ReadoutWireDirection;
  description: string;
  threshold?: ReadoutWireThreshold;
}
