/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

export type ReadoutType = typeof ReadoutType[keyof typeof ReadoutType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReadoutType = {
  numeric: 'numeric',
  probability: 'probability',
  class: 'class',
} as const;
