/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { ReplicateSummaryResponseMean } from './replicateSummaryResponseMean';
import type { ReplicateSummaryResponseSd } from './replicateSummaryResponseSd';

/**
 * One metric's mean and spread across the extra split draws that defined it.
 */
export interface ReplicateSummaryResponse {
  mean: ReplicateSummaryResponseMean;
  sd: ReplicateSummaryResponseSd;
  n: number;
}
