/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */

/**
 * `edges` is one longer than `counts`.

Named for what it holds rather than for its shape, because `datasets.py`
also declares a `HistogramResponse` and two identically-named schemas in one
OpenAPI document generate a client with both of them renamed to their fully
qualified module paths.
 */
export interface ResidualHistogramResponse {
  edges: number[];
  counts: number[];
}
