/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { RevisePageBodyBody } from './revisePageBodyBody';

export interface RevisePageBody {
  body: RevisePageBodyBody;
  expected_version: number;
}
