/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { RunChemicalSpaceResponseStatus } from './runChemicalSpaceResponseStatus';
import type { RunChemicalSpaceResponsePoints } from './runChemicalSpaceResponsePoints';
import type { RunChemicalSpaceResponseSummary } from './runChemicalSpaceResponseSummary';

export interface RunChemicalSpaceResponse {
  status: RunChemicalSpaceResponseStatus;
  points?: RunChemicalSpaceResponsePoints;
  summary?: RunChemicalSpaceResponseSummary;
}
