/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

export type RunChemicalSpaceResponseStatus = typeof RunChemicalSpaceResponseStatus[keyof typeof RunChemicalSpaceResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RunChemicalSpaceResponseStatus = {
  ready: 'ready',
  missing: 'missing',
} as const;
