/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { RunMapSummaryResponse } from './runMapSummaryResponse';

export type RunChemicalSpaceResponseSummary = RunMapSummaryResponse | null;
