/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { RunMapPointsResponse } from './runMapPointsResponse';

export type RunChemicalSpaceResponsePoints = RunMapPointsResponse | null;
