/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { RunChemicalSpaceResponseStatus } from './runChemicalSpaceResponseStatus';
import type { RunChemicalSpaceResponsePoints } from './runChemicalSpaceResponsePoints';
import type { RunChemicalSpaceResponseSummary } from './runChemicalSpaceResponseSummary';

export interface RunChemicalSpaceResponse {
  status: RunChemicalSpaceResponseStatus;
  points?: RunChemicalSpaceResponsePoints;
  summary?: RunChemicalSpaceResponseSummary;
}
