/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */

export type RunChemicalSpaceResponseStatus = typeof RunChemicalSpaceResponseStatus[keyof typeof RunChemicalSpaceResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RunChemicalSpaceResponseStatus = {
  ready: 'ready',
  missing: 'missing',
} as const;
