/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { RunEnvelopeParams } from './runEnvelopeParams';
import type { RunEnvelopeProtocolId } from './runEnvelopeProtocolId';
import type { RunEnvelopePhase } from './runEnvelopePhase';
import type { RunEnvelopeResultUri } from './runEnvelopeResultUri';
import type { RunEnvelopeErrorMessage } from './runEnvelopeErrorMessage';
import type { RunEnvelopeSweepId } from './runEnvelopeSweepId';
import type { RunEnvelopeMetrics } from './runEnvelopeMetrics';

/**
 * Mirrors every `Run.__init__` kwarg (`domain/execution/run.py`).
 */
export interface RunEnvelope {
  id: string;
  kind: string;
  workspace_id: string;
  requested_by: string;
  cache_key: string;
  params: RunEnvelopeParams;
  protocol_id: RunEnvelopeProtocolId;
  status: string;
  progress: number;
  phase: RunEnvelopePhase;
  result_uri: RunEnvelopeResultUri;
  error_message: RunEnvelopeErrorMessage;
  created_at: string;
  updated_at: string;
  version: number;
  sweep_id?: RunEnvelopeSweepId;
  metrics?: RunEnvelopeMetrics;
}
