/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { RunEnvelopeMetricsAnyOf } from './runEnvelopeMetricsAnyOf';

export type RunEnvelopeMetrics = RunEnvelopeMetricsAnyOf | null;
