/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */

export type RunKind = typeof RunKind[keyof typeof RunKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RunKind = {
  training: 'training',
  prediction: 'prediction',
} as const;
