/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

export type RunKind = typeof RunKind[keyof typeof RunKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RunKind = {
  training: 'training',
  prediction: 'prediction',
} as const;
