/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { RunMapPointsResponseApplicabilityItem } from './runMapPointsResponseApplicabilityItem';

/**
 * One entry per scored compound, in results-file order (`row_id`). `x`/`y` are
the similarity-weighted centre of `neighbors`, which index the protocol map's
points; `applicability` is the true Tanimoto to the nearest of them.
 */
export interface RunMapPointsResponse {
  x: number[];
  y: number[];
  row_id: number[];
  applicability: RunMapPointsResponseApplicabilityItem[];
  neighbors: number[][];
}
