/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { RunMapCompoundResponseCompoundId } from './runMapCompoundResponseCompoundId';
import type { RunMapCompoundResponseValues } from './runMapCompoundResponseValues';
import type { RunMapCompoundResponseApplicability } from './runMapCompoundResponseApplicability';

export interface RunMapCompoundResponse {
  row_id: number;
  structure: string;
  compound_id: RunMapCompoundResponseCompoundId;
  values: RunMapCompoundResponseValues;
  applicability: RunMapCompoundResponseApplicability;
}
