/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { RunMetricsWireValue } from './runMetricsWireValue';
import type { RunMetricsWireBaselineValue } from './runMetricsWireBaselineValue';

/**
 * Mirrors the exact three keys `Run.record_metrics` writes
(`domain/execution/run.py`) -- the only shape a runner-reported `metrics`
payload is allowed to take.

A free `dict[str, Any]` here would let a self-hosted runner store
arbitrary JSON verbatim in the `runs.metrics` column, inside the same
security boundary the module docstring calls out. Pinning the shape
means a malformed payload is a 422 at the edge, not a write.
 */
export interface RunMetricsWire {
  primary_metric: string;
  value: RunMetricsWireValue;
  baseline_value: RunMetricsWireBaselineValue;
}
