/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { TargetHeadlineWire } from './targetHeadlineWire';

/**
 * Mirrors exactly what `Run.record_metrics` writes (`domain/execution/run.py`):
one headline per target -- the only shape a runner-reported training `metrics`
payload may take.

A free `dict[str, Any]` here would let a self-hosted runner store
arbitrary JSON verbatim in the `runs.metrics` column, inside the same
security boundary the module docstring calls out. Pinning the shape
means a malformed payload is a 422 at the edge, not a write.
 */
export interface RunMetricsWire {
  /** @maxItems 4096 */
  targets: TargetHeadlineWire[];
}
