/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { RunMapSummaryResponseNearestMin } from './runMapSummaryResponseNearestMin';
import type { RunMapSummaryResponseNearestMax } from './runMapSummaryResponseNearestMax';

export interface RunMapSummaryResponse {
  total: number;
  in_domain: number;
  threshold: number;
  nearest_min: RunMapSummaryResponseNearestMin;
  nearest_max: RunMapSummaryResponseNearestMax;
}
