/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { RunnerResponseLastSeenAt } from './runnerResponseLastSeenAt';
import type { RunnerResponseCurrentRunId } from './runnerResponseCurrentRunId';

export interface RunnerResponse {
  id: string;
  name: string;
  lanes: string[];
  online: boolean;
  last_seen_at: RunnerResponseLastSeenAt;
  revoked: boolean;
  current_run_id: RunnerResponseCurrentRunId;
  created_at: string;
}
