/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { RunResponsePhase } from './runResponsePhase';
import type { RunResponseResultUri } from './runResponseResultUri';
import type { RunResponseErrorMessage } from './runResponseErrorMessage';
import type { RunResponseProtocolId } from './runResponseProtocolId';
import type { RunResponseMetrics } from './runResponseMetrics';
import type { RunResponseLane } from './runResponseLane';
import type { RunResponseName } from './runResponseName';

export interface RunResponse {
  id: string;
  workspace_id: string;
  kind: string;
  status: string;
  progress: number;
  phase: RunResponsePhase;
  result_uri: RunResponseResultUri;
  error_message: RunResponseErrorMessage;
  protocol_id: RunResponseProtocolId;
  metrics: RunResponseMetrics;
  lane: RunResponseLane;
  name: RunResponseName;
  created_at: string;
}
