/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { RunResponseMetricsAnyOf } from './runResponseMetricsAnyOf';

export type RunResponseMetrics = RunResponseMetricsAnyOf | null;
