/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

export type RunStatus = typeof RunStatus[keyof typeof RunStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RunStatus = {
  pending: 'pending',
  running: 'running',
  ready: 'ready',
  failed: 'failed',
  cancelled: 'cancelled',
} as const;
