/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

/**
 * Where a prediction run's compounds came from, when not from an uploaded file.
 */
export interface RunSourceResponse {
  app: 'chemcellar';
  run_id: string;
  protocol_id: string;
  protocol_name: string;
  run_date: string;
  compounds_without_structure?: number;
}
