/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { RunMetricsWire } from './runMetricsWire';
import type { PredictionCountsWire } from './predictionCountsWire';

export type RunUpdateEnvelopeMetrics = RunMetricsWire | PredictionCountsWire | null;
