/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { RunUpdateEnvelopeProgress } from './runUpdateEnvelopeProgress';
import type { RunUpdateEnvelopePhase } from './runUpdateEnvelopePhase';
import type { RunUpdateEnvelopeResultUri } from './runUpdateEnvelopeResultUri';
import type { RunUpdateEnvelopeErrorMessage } from './runUpdateEnvelopeErrorMessage';
import type { RunUpdateEnvelopeProtocolId } from './runUpdateEnvelopeProtocolId';
import type { RunUpdateEnvelopeMetrics } from './runUpdateEnvelopeMetrics';

/**
 * Only the mutable fields a handler writes back while a run is in
flight -- not a full `Run` mirror, so no `to_domain`. `expected_version`
carries the optimistic-concurrency check the repository's `update()`
already enforces (see `infrastructure/persistence/sqlalchemy/execution/
repository.py`).

`status` and `expected_version` are the only required fields.  Every
other field defaults to `None` and is applied only when the caller
actually sent it (`interface/routes/runner_api.py` checks
`model_fields_set`) -- a required-and-nullable field here would mean any
update that legitimately omits `phase`/`progress`/etc. (e.g. a bare
heartbeat-style status flip) silently nulls out whatever the previous
update had reported, which is what the security review's Important 1
finding caught in practice (progress 0.9 -> 0.0, phase "fit" -> None).
 */
export interface RunUpdateEnvelope {
  status: string;
  expected_version: number;
  progress?: RunUpdateEnvelopeProgress;
  phase?: RunUpdateEnvelopePhase;
  result_uri?: RunUpdateEnvelopeResultUri;
  error_message?: RunUpdateEnvelopeErrorMessage;
  protocol_id?: RunUpdateEnvelopeProtocolId;
  metrics?: RunUpdateEnvelopeMetrics;
}
