/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { ScaffoldEntryResponse } from './scaffoldEntryResponse';

export interface ScaffoldProfileResponse {
  unique_count: number;
  singleton_count: number;
  largest_fraction: number;
  cumulative_coverage: number[];
  top: ScaffoldEntryResponse[];
  cross_split_scaffolds: number;
  cross_split_compounds: number;
}
