/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { ScaffoldEntryResponse } from './scaffoldEntryResponse';

export interface ScaffoldProfileResponse {
  unique_count: number;
  singleton_count: number;
  largest_fraction: number;
  cumulative_coverage: number[];
  top: ScaffoldEntryResponse[];
  cross_split_scaffolds: number;
  cross_split_compounds: number;
}
