/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { ScorecardResponseMetricsUndefinedAnyOf } from './scorecardResponseMetricsUndefinedAnyOf';

export type ScorecardResponseMetricsUndefined = ScorecardResponseMetricsUndefinedAnyOf | null;
