/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { ResidualHistogramResponse } from './residualHistogramResponse';

export type ScorecardResponseResidualHistogram = ResidualHistogramResponse | null;
