/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { ScorecardResponseRandomSplitMetricsAnyOf } from './scorecardResponseRandomSplitMetricsAnyOf';

export type ScorecardResponseRandomSplitMetrics = ScorecardResponseRandomSplitMetricsAnyOf | null;
