/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { ReplicateSummaryResponse } from './replicateSummaryResponse';

export type ScorecardResponseReplicateSummaryAnyOf = {[key: string]: ReplicateSummaryResponse};
