/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { ScorecardResponseRandomSplitMetricsUndefinedAnyOf } from './scorecardResponseRandomSplitMetricsUndefinedAnyOf';

export type ScorecardResponseRandomSplitMetricsUndefined = ScorecardResponseRandomSplitMetricsUndefinedAnyOf | null;
