/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { ScorecardResponseMetrics } from './scorecardResponseMetrics';
import type { ScorecardResponseMetricsUndefined } from './scorecardResponseMetricsUndefined';
import type { ScorecardResponseConditions } from './scorecardResponseConditions';
import type { ScorecardResponseBaselineConditions } from './scorecardResponseBaselineConditions';
import type { ScorecardResponseBaselineMetrics } from './scorecardResponseBaselineMetrics';
import type { ScorecardResponseRandomSplitMetrics } from './scorecardResponseRandomSplitMetrics';
import type { ScorecardResponseRandomSplitUnavailable } from './scorecardResponseRandomSplitUnavailable';
import type { ScorecardResponseRandomSplitMetricsUndefined } from './scorecardResponseRandomSplitMetricsUndefined';
import type { ScorecardResponseNoiseFloor } from './scorecardResponseNoiseFloor';
import type { WorstRowResponse } from './worstRowResponse';
import type { ScorecardResponseApplicabilityCoverage } from './scorecardResponseApplicabilityCoverage';
import type { ScorecardResponseUnit } from './scorecardResponseUnit';
import type { ScorecardResponseDirection } from './scorecardResponseDirection';

/**
 * Every field here is load-bearing for honest rendering -- see
`domain/execution/scorecard.py`'s docstring for what each one means and
why it exists. In particular: `baseline_is_self` true means the chosen
engine *is* the baseline (render "this model is the baseline", not a
head-to-head that never happened); `metrics_undefined` is why a metric in
`metrics` reads `null` instead of a number; `random_split_unavailable`
distinguishes "not applicable" (`None`/`None`) from "could not be
computed" (`None`/a reason) for `random_split_metrics`;
`random_split_metrics_undefined` is `metrics_undefined`'s own counterpart
for `random_split_metrics` -- a *different* partition that can disagree
with the Dataset's own split about which metrics are undefined and why,
so a renderer must not reuse `metrics_undefined` to explain a
`random_split_metrics` null.

`unit`/`direction` are the target's own -- what `metrics`, `worst_rows`'
`actual`/`predicted`/`residual`, and `noise_floor` are all measured in, and
which way is better. `split_strategy` (`"random"` or `"scaffold"`) is
which split produced `metrics`/`baseline_metrics`/`worst_rows` -- read this
instead of inferring it from `random_split_metrics`/
`random_split_unavailable` both being `None`.
 */
export interface ScorecardResponse {
  primary_metric: string;
  prediction_kind: string;
  metrics: ScorecardResponseMetrics;
  metrics_undefined: ScorecardResponseMetricsUndefined;
  engine_id: string;
  conditions: ScorecardResponseConditions;
  baseline_engine_id: string;
  baseline_conditions: ScorecardResponseBaselineConditions;
  baseline_metrics: ScorecardResponseBaselineMetrics;
  baseline_is_self: boolean;
  random_split_metrics: ScorecardResponseRandomSplitMetrics;
  random_split_unavailable: ScorecardResponseRandomSplitUnavailable;
  random_split_metrics_undefined: ScorecardResponseRandomSplitMetricsUndefined;
  noise_floor: ScorecardResponseNoiseFloor;
  worst_rows: WorstRowResponse[];
  applicability_coverage: ScorecardResponseApplicabilityCoverage;
  unit: ScorecardResponseUnit;
  direction: ScorecardResponseDirection;
  split_strategy: string;
}
