/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { RegressionSummaryResponse } from './regressionSummaryResponse';

export type ScorecardResponseRegressionSummary = RegressionSummaryResponse | null;
