/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { ScorecardResponseValidationMetricsAnyOf } from './scorecardResponseValidationMetricsAnyOf';

export type ScorecardResponseValidationMetrics = ScorecardResponseValidationMetricsAnyOf | null;
