/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { ScorecardResponseReplicateSummaryAnyOf } from './scorecardResponseReplicateSummaryAnyOf';

export type ScorecardResponseReplicateSummary = ScorecardResponseReplicateSummaryAnyOf | null;
