/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { BootstrapHistogramResponse } from './bootstrapHistogramResponse';

export type ScorecardResponseDifferenceBootstrap = BootstrapHistogramResponse | null;
