/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { ScorecardResponsePrimaryMetricCi } from './scorecardResponsePrimaryMetricCi';
import type { ScorecardResponsePrimaryMetricBootstrap } from './scorecardResponsePrimaryMetricBootstrap';
import type { ScorecardResponseMetrics } from './scorecardResponseMetrics';
import type { ScorecardResponseValidationMetrics } from './scorecardResponseValidationMetrics';
import type { ScorecardResponseMetricsUndefined } from './scorecardResponseMetricsUndefined';
import type { ScorecardResponseConditions } from './scorecardResponseConditions';
import type { ScorecardResponseBaselineConditions } from './scorecardResponseBaselineConditions';
import type { ScorecardResponseBaselineMetrics } from './scorecardResponseBaselineMetrics';
import type { ScorecardResponseRandomSplitMetrics } from './scorecardResponseRandomSplitMetrics';
import type { ScorecardResponseRandomSplitUnavailable } from './scorecardResponseRandomSplitUnavailable';
import type { ScorecardResponseRandomSplitMetricsUndefined } from './scorecardResponseRandomSplitMetricsUndefined';
import type { ScorecardResponseNoiseFloor } from './scorecardResponseNoiseFloor';
import type { WorstRowResponse } from './worstRowResponse';
import type { ScorecardResponseApplicabilityCoverage } from './scorecardResponseApplicabilityCoverage';
import type { ScorecardResponseUnit } from './scorecardResponseUnit';
import type { ScorecardResponseDirection } from './scorecardResponseDirection';
import type { ScorecardResponseCutoff } from './scorecardResponseCutoff';
import type { ScorecardResponseBaselineCutoff } from './scorecardResponseBaselineCutoff';
import type { ScorecardResponseCutoffNote } from './scorecardResponseCutoffNote';
import type { ParityPointResponse } from './parityPointResponse';
import type { ScorecardResponseParitySampledFrom } from './scorecardResponseParitySampledFrom';
import type { ScorecardResponseResidualHistogram } from './scorecardResponseResidualHistogram';
import type { BinResponse } from './binResponse';
import type { ScaffoldErrorResponse } from './scaffoldErrorResponse';

/**
 * One card per target; `joint_model` says whether one model learned them all.

Every field here is load-bearing for honest rendering -- see
`domain/execution/scorecard.py`'s docstring for what each one means and
why it exists. In particular: `baseline_is_self` true means the chosen
engine *is* the baseline (render "this model is the baseline", not a
head-to-head that never happened); `metrics_undefined` is why a metric in
`metrics` reads `null` instead of a number; `random_split_unavailable`
distinguishes "not applicable" (`None`/`None`) from "could not be
computed" (`None`/a reason) for `random_split_metrics`;
`random_split_metrics_undefined` is `metrics_undefined`'s own counterpart
for `random_split_metrics` -- a *different* partition that can disagree
with the Dataset's own split about which metrics are undefined and why,
so a renderer must not reuse `metrics_undefined` to explain a
`random_split_metrics` null.

`unit`/`direction` are the target's own -- what `metrics`, `worst_rows`'
`actual`/`predicted`/`residual`, and `noise_floor` are all measured in, and
which way is better. `split_strategy` (`"random"` or `"scaffold"`) is
which split produced `metrics`/`baseline_metrics`/`worst_rows` -- read this
instead of inferring it from `random_split_metrics`/
`random_split_unavailable` both being `None`.
 */
export interface ScorecardResponse {
  target: string;
  joint_model: boolean;
  primary_metric: string;
  primary_metric_ci: ScorecardResponsePrimaryMetricCi;
  primary_metric_bootstrap: ScorecardResponsePrimaryMetricBootstrap;
  prediction_kind: string;
  metrics: ScorecardResponseMetrics;
  validation_metrics: ScorecardResponseValidationMetrics;
  metrics_undefined: ScorecardResponseMetricsUndefined;
  engine_id: string;
  conditions: ScorecardResponseConditions;
  baseline_engine_id: string;
  baseline_conditions: ScorecardResponseBaselineConditions;
  baseline_metrics: ScorecardResponseBaselineMetrics;
  baseline_is_self: boolean;
  random_split_metrics: ScorecardResponseRandomSplitMetrics;
  random_split_unavailable: ScorecardResponseRandomSplitUnavailable;
  random_split_metrics_undefined: ScorecardResponseRandomSplitMetricsUndefined;
  noise_floor: ScorecardResponseNoiseFloor;
  worst_rows: WorstRowResponse[];
  applicability_coverage: ScorecardResponseApplicabilityCoverage;
  unit: ScorecardResponseUnit;
  direction: ScorecardResponseDirection;
  split_strategy: string;
  cutoff: ScorecardResponseCutoff;
  baseline_cutoff: ScorecardResponseBaselineCutoff;
  cutoff_note: ScorecardResponseCutoffNote;
  parity: ParityPointResponse[];
  parity_sampled_from: ScorecardResponseParitySampledFrom;
  residual_histogram: ScorecardResponseResidualHistogram;
  error_by_similarity: BinResponse[];
  scaffold_errors: ScaffoldErrorResponse[];
  calibration: BinResponse[];
}
