/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { ScorecardResponseBaselineMetricsAnyOf } from './scorecardResponseBaselineMetricsAnyOf';

export type ScorecardResponseBaselineMetrics = ScorecardResponseBaselineMetricsAnyOf | null;
