/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { ClassificationSummaryResponse } from './classificationSummaryResponse';

export type ScorecardResponseClassificationSummary = ClassificationSummaryResponse | null;
