/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { BootstrapHistogramResponse } from './bootstrapHistogramResponse';

export type ScorecardResponsePrimaryMetricBootstrap = BootstrapHistogramResponse | null;
