/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { ToleranceBinResponse } from './toleranceBinResponse';

export interface ScorecardToleranceResponse {
  target: string;
  tolerance: number;
  within_count: number;
  test_count: number;
  by_similarity: ToleranceBinResponse[];
}
