/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { SetIdColumnBodyIdColumn } from './setIdColumnBodyIdColumn';

export interface SetIdColumnBody {
  id_column: SetIdColumnBodyIdColumn;
}
