/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { HistogramResponse } from './histogramResponse';

export interface SimilarityProfileResponse {
  histogram: HistogramResponse;
  median: number;
  within_domain: number;
  within_domain_threshold: number;
  near_duplicates: number;
  near_duplicate_threshold: number;
}
