/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { HistogramResponse } from './histogramResponse';

export interface SimilarityProfileResponse {
  histogram: HistogramResponse;
  median: number;
  within_domain: number;
  within_domain_threshold: number;
  near_duplicates: number;
  near_duplicate_threshold: number;
}
