/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

/**
 * Train and test counts over shared edges, so the two can be overlaid.
 */
export interface SplitHistogramResponse {
  edges: number[];
  train: number[];
  test: number[];
}
