/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */

export type SplitStrategy = typeof SplitStrategy[keyof typeof SplitStrategy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SplitStrategy = {
  random: 'random',
  scaffold: 'scaffold',
} as const;
