/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

export type SplitStrategy = typeof SplitStrategy[keyof typeof SplitStrategy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SplitStrategy = {
  random: 'random',
  scaffold: 'scaffold',
  identity: 'identity',
  position: 'position',
  predefined: 'predefined',
} as const;
