/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { SplitStrategy } from './splitStrategy';
import type { SplitBodyColumn } from './splitBodyColumn';

export interface SplitBody {
  strategy: SplitStrategy;
  seed: number;
  /**
   * @minItems 3
   * @maxItems 3
   */
  fractions?: [number, number, number];
  column?: SplitBodyColumn;
}
