/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { SplitSpecWireColumn } from './splitSpecWireColumn';

/**
 * Mirrors `SplitSpec` (`domain/data/split.py`).
 */
export interface SplitSpecWire {
  strategy: string;
  seed: number;
  /**
   * @minItems 3
   * @maxItems 3
   */
  fractions?: [number, number, number];
  column?: SplitSpecWireColumn;
}
