/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { SplitStrategy } from './splitStrategy';

export interface SplitBody {
  strategy: SplitStrategy;
  seed: number;
  /**
   * @minItems 3
   * @maxItems 3
   */
  fractions?: [number, number, number];
}
