/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */

/**
 * Train and test counts over shared edges, so the two can be overlaid.
 */
export interface SplitHistogramResponse {
  edges: number[];
  train: number[];
  test: number[];
}
