/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { SweepConfigBody } from './sweepConfigBody';
import type { SubmitSweepBodyBaselineEngineId } from './submitSweepBodyBaselineEngineId';
import type { SubmitSweepBodyBaselineConditions } from './submitSweepBodyBaselineConditions';

export interface SubmitSweepBody {
  /**
   * @minLength 1
   * @maxLength 200
   */
  name: string;
  dataset_id: string;
  /**
   * @minItems 1
   * @maxItems 50
   */
  configs: SweepConfigBody[];
  baseline_engine_id?: SubmitSweepBodyBaselineEngineId;
  baseline_conditions?: SubmitSweepBodyBaselineConditions;
  tune_cutoffs?: boolean;
}
