/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

export interface SubstitutionResponse {
  position: number;
  wild_type: string;
  variant: string;
  value: number;
  split: string;
}
