/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { SweepRunResponseMetricsAnyOf } from './sweepRunResponseMetricsAnyOf';

export type SweepRunResponseMetrics = SweepRunResponseMetricsAnyOf | null;
