/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { SweepResponseName } from './sweepResponseName';
import type { SweepResponseDatasetId } from './sweepResponseDatasetId';
import type { SweepResponseByStatus } from './sweepResponseByStatus';

export interface SweepResponse {
  sweep_id: string;
  name: SweepResponseName;
  dataset_id: SweepResponseDatasetId;
  created_at: string;
  total: number;
  by_status: SweepResponseByStatus;
}
