/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { SweepDetailResponseName } from './sweepDetailResponseName';
import type { SweepDetailResponseDatasetId } from './sweepDetailResponseDatasetId';
import type { SweepRunResponse } from './sweepRunResponse';

export interface SweepDetailResponse {
  sweep_id: string;
  name: SweepDetailResponseName;
  dataset_id: SweepDetailResponseDatasetId;
  runs: SweepRunResponse[];
}
