/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { SweepDetailResponseName } from './sweepDetailResponseName';
import type { SweepDetailResponseDatasetId } from './sweepDetailResponseDatasetId';
import type { SweepRunResponse } from './sweepRunResponse';

export interface SweepDetailResponse {
  sweep_id: string;
  name: SweepDetailResponseName;
  dataset_id: SweepDetailResponseDatasetId;
  runs: SweepRunResponse[];
}
