/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { SweepConfigBodyConditions } from './sweepConfigBodyConditions';

export interface SweepConfigBody {
  engine_id: string;
  conditions?: SweepConfigBodyConditions;
}
