/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { SweepRunResponseSweepId } from './sweepRunResponseSweepId';
import type { SweepRunResponseConditions } from './sweepRunResponseConditions';
import type { SweepRunResponsePhase } from './sweepRunResponsePhase';
import type { SweepRunResponseErrorMessage } from './sweepRunResponseErrorMessage';
import type { SweepRunResponseProtocolId } from './sweepRunResponseProtocolId';
import type { SweepRunResponseMetrics } from './sweepRunResponseMetrics';

export interface SweepRunResponse {
  id: string;
  sweep_id: SweepRunResponseSweepId;
  name: string;
  engine_id: string;
  conditions: SweepRunResponseConditions;
  status: string;
  progress: number;
  phase: SweepRunResponsePhase;
  error_message: SweepRunResponseErrorMessage;
  protocol_id: SweepRunResponseProtocolId;
  metrics: SweepRunResponseMetrics;
  created_at: string;
}
