/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { TargetSpecWireUnit } from './targetSpecWireUnit';
import type { TargetSpecWireDirection } from './targetSpecWireDirection';

/**
 * Mirrors `TargetSpec` (`domain/data/target.py`).
 */
export interface TargetSpecWire {
  column: string;
  kind: string;
  unit?: TargetSpecWireUnit;
  direction?: TargetSpecWireDirection;
}
