/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { TargetSpecWireUnit } from './targetSpecWireUnit';
import type { TargetSpecWireDirection } from './targetSpecWireDirection';

/**
 * Mirrors `TargetSpec` (`domain/data/target.py`).
 */
export interface TargetSpecWire {
  column: string;
  kind: string;
  unit?: TargetSpecWireUnit;
  direction?: TargetSpecWireDirection;
}
