/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { SplitHistogramResponse } from './splitHistogramResponse';
import type { NumericSummaryResponse } from './numericSummaryResponse';

export interface TargetDistributionResponse {
  histogram: SplitHistogramResponse;
  train: NumericSummaryResponse;
  test: NumericSummaryResponse;
}
