/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { TargetKind } from './targetKind';
import type { TargetBodyUnit } from './targetBodyUnit';
import type { TargetBodyDirection } from './targetBodyDirection';

export interface TargetBody {
  column: string;
  kind: TargetKind;
  unit?: TargetBodyUnit;
  direction?: TargetBodyDirection;
}
