/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { TargetKind } from './targetKind';
import type { TargetBodyUnit } from './targetBodyUnit';
import type { TargetBodyDirection } from './targetBodyDirection';

export interface TargetBody {
  column: string;
  kind: TargetKind;
  unit?: TargetBodyUnit;
  direction?: TargetBodyDirection;
}
