/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

export type TargetKind = typeof TargetKind[keyof typeof TargetKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TargetKind = {
  numeric: 'numeric',
  binary: 'binary',
} as const;
