/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */

export type TargetKind = typeof TargetKind[keyof typeof TargetKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TargetKind = {
  numeric: 'numeric',
  binary: 'binary',
} as const;
