/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */

export interface TargetClassBalanceResponse {
  split: string;
  positive: number;
  negative: number;
  column: string;
  labelled?: number;
}
