/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { TargetHeadlineWireValue } from './targetHeadlineWireValue';
import type { TargetHeadlineWireBaselineValue } from './targetHeadlineWireBaselineValue';

export interface TargetHeadlineWire {
  /** @maxLength 1024 */
  column: string;
  /** @maxLength 64 */
  primary_metric: string;
  value: TargetHeadlineWireValue;
  baseline_value: TargetHeadlineWireBaselineValue;
}
