/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { TrainProtocolBodyConditions } from './trainProtocolBodyConditions';
import type { TrainProtocolBodyBaselineEngineId } from './trainProtocolBodyBaselineEngineId';
import type { TrainProtocolBodyBaselineConditions } from './trainProtocolBodyBaselineConditions';
import type { TrainProtocolBodySubsetColumn } from './trainProtocolBodySubsetColumn';

export interface TrainProtocolBody {
  /** @maxLength 256 */
  name: string;
  dataset_id: string;
  engine_id: string;
  conditions: TrainProtocolBodyConditions;
  baseline_engine_id?: TrainProtocolBodyBaselineEngineId;
  baseline_conditions?: TrainProtocolBodyBaselineConditions;
  tune_cutoffs?: boolean;
  run_baseline?: boolean;
  optimism_gap?: boolean;
  subset_column?: TrainProtocolBodySubsetColumn;
}
