/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { TrainProtocolBodyConditions } from './trainProtocolBodyConditions';
import type { TrainProtocolBodyBaselineEngineId } from './trainProtocolBodyBaselineEngineId';
import type { TrainProtocolBodyBaselineConditions } from './trainProtocolBodyBaselineConditions';

export interface TrainProtocolBody {
  /** @maxLength 256 */
  name: string;
  dataset_id: string;
  engine_id: string;
  conditions: TrainProtocolBodyConditions;
  baseline_engine_id?: TrainProtocolBodyBaselineEngineId;
  baseline_conditions?: TrainProtocolBodyBaselineConditions;
  tune_cutoffs?: boolean;
}
