/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { InvalidRow } from './invalidRow';
import type { ConflictRow } from './conflictRow';
import type { ValidationReportWireDuplicateSpread } from './validationReportWireDuplicateSpread';

/**
 * Mirrors `ValidationReport` (`domain/data/validation.py`).

`invalid`/`conflicting` type straight to the domain's own `InvalidRow`/
`ConflictRow` frozen dataclasses -- pydantic validates and serializes
plain dataclasses natively, so a dedicated wire mirror for each would be
pure duplication of fields that carry no enum and need no cast.
 */
export interface ValidationReportWire {
  total_rows: number;
  valid_rows: number;
  invalid?: InvalidRow[];
  conflicting?: ConflictRow[];
  duplicates_collapsed?: number;
  salts_flagged?: number;
  duplicate_spread?: ValidationReportWireDuplicateSpread;
}
