/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { InvalidRowResponse } from './invalidRowResponse';
import type { ConflictRowResponse } from './conflictRowResponse';
import type { ValidationReportResponseDuplicateSpread } from './validationReportResponseDuplicateSpread';

/**
 * The report, typed rather than a bare `dict`.

It reaches a client by two routes -- on an accepted `DatasetResponse`, and
as the `detail` of the 422 that `InvalidDatasetError` raises when a file is
refused at the door. The rejection is the case that matters: which rows
failed and why, how many duplicates collapsed, how wide the assay spread
was, is the whole value of the validation pass, and a UI cannot render any
of it from `dict[str, Any]`. The error path serialises the same dataclasses
through `report_to_dict`, so both bodies share this shape even though only
this one appears in the OpenAPI contract.
 */
export interface ValidationReportResponse {
  total_rows: number;
  valid_rows: number;
  invalid: InvalidRowResponse[];
  conflicting: ConflictRowResponse[];
  duplicates_collapsed: number;
  salts_flagged: number;
  duplicate_spread: ValidationReportResponseDuplicateSpread;
}
