/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { VariantPositionResponse } from './variantPositionResponse';
import type { SubstitutionResponse } from './substitutionResponse';
import type { VariantProfileResponsePositionsSampledFrom } from './variantProfileResponsePositionsSampledFrom';

/**
 * Where a single-parent variant series varies. Present only for sequences.

The sequence counterpart of `scaffolds`, and read the same way: `positions` is the
composition of the dataset, and a position appearing in both training and test is
the same integrity failure a scaffold spanning partitions would be.
 */
export interface VariantProfileResponse {
  consensus: string;
  positions: VariantPositionResponse[];
  unchanged_rows: number;
  multi_mutant_rows: number;
  held_out_positions: number;
  substitutions?: SubstitutionResponse[];
  positions_sampled_from?: VariantProfileResponsePositionsSampledFrom;
}
