/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import type { WorstRowResponseSimilarity } from './worstRowResponseSimilarity';
import type { WorstRowResponseCompoundId } from './worstRowResponseCompoundId';

export interface WorstRowResponse {
  structure: string;
  actual: number;
  predicted: number;
  residual: number;
  scaffold: string;
  similarity: WorstRowResponseSimilarity;
  compound_id: WorstRowResponseCompoundId;
}
