/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import type { WorstRowResponseSimilarity } from './worstRowResponseSimilarity';
import type { WorstRowResponseCompoundId } from './worstRowResponseCompoundId';

export interface WorstRowResponse {
  structure: string;
  actual: number;
  predicted: number;
  residual: number;
  scaffold: string;
  similarity: WorstRowResponseSimilarity;
  compound_id: WorstRowResponseCompoundId;
}
