/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetRunResultsApiV1RunsRunIdResultsGetParams,
  HTTPValidationError,
  ListRunsApiV1RunsGetParams,
  PaginatedResponsePredictionResponse,
  PaginatedResponseRunResponse,
  PredictBody,
  RunResponse
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * @summary Create Run
 */
export const createRunApiV1RunsPost = (
    predictBody: PredictBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<RunResponse>(
      {url: `/api/v1/runs`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: predictBody, signal
    },
      );
    }
  


export const getCreateRunApiV1RunsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRunApiV1RunsPost>>, TError,{data: PredictBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createRunApiV1RunsPost>>, TError,{data: PredictBody}, TContext> => {

const mutationKey = ['createRunApiV1RunsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createRunApiV1RunsPost>>, {data: PredictBody}> = (props) => {
          const {data} = props ?? {};

          return  createRunApiV1RunsPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateRunApiV1RunsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createRunApiV1RunsPost>>>
    export type CreateRunApiV1RunsPostMutationBody = PredictBody
    export type CreateRunApiV1RunsPostMutationError = HTTPValidationError

    /**
 * @summary Create Run
 */
export const useCreateRunApiV1RunsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRunApiV1RunsPost>>, TError,{data: PredictBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createRunApiV1RunsPost>>,
        TError,
        {data: PredictBody},
        TContext
      > => {

      const mutationOptions = getCreateRunApiV1RunsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Declared before `/{run_id}` so the empty path is not swallowed by the
id route -- Starlette matches in declaration order.
 * @summary List Runs
 */
export const listRunsApiV1RunsGet = (
    params?: ListRunsApiV1RunsGetParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PaginatedResponseRunResponse>(
      {url: `/api/v1/runs`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListRunsApiV1RunsGetQueryKey = (params?: ListRunsApiV1RunsGetParams,) => {
    return [
    `/api/v1/runs`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListRunsApiV1RunsGetQueryOptions = <TData = Awaited<ReturnType<typeof listRunsApiV1RunsGet>>, TError = HTTPValidationError>(params?: ListRunsApiV1RunsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRunsApiV1RunsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListRunsApiV1RunsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listRunsApiV1RunsGet>>> = ({ signal }) => listRunsApiV1RunsGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listRunsApiV1RunsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListRunsApiV1RunsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listRunsApiV1RunsGet>>>
export type ListRunsApiV1RunsGetQueryError = HTTPValidationError


export function useListRunsApiV1RunsGet<TData = Awaited<ReturnType<typeof listRunsApiV1RunsGet>>, TError = HTTPValidationError>(
 params: undefined |  ListRunsApiV1RunsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRunsApiV1RunsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRunsApiV1RunsGet>>,
          TError,
          Awaited<ReturnType<typeof listRunsApiV1RunsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListRunsApiV1RunsGet<TData = Awaited<ReturnType<typeof listRunsApiV1RunsGet>>, TError = HTTPValidationError>(
 params?: ListRunsApiV1RunsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRunsApiV1RunsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRunsApiV1RunsGet>>,
          TError,
          Awaited<ReturnType<typeof listRunsApiV1RunsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListRunsApiV1RunsGet<TData = Awaited<ReturnType<typeof listRunsApiV1RunsGet>>, TError = HTTPValidationError>(
 params?: ListRunsApiV1RunsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRunsApiV1RunsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Runs
 */

export function useListRunsApiV1RunsGet<TData = Awaited<ReturnType<typeof listRunsApiV1RunsGet>>, TError = HTTPValidationError>(
 params?: ListRunsApiV1RunsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRunsApiV1RunsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListRunsApiV1RunsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get Run
 */
export const getRunApiV1RunsRunIdGet = (
    runId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<RunResponse>(
      {url: `/api/v1/runs/${runId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetRunApiV1RunsRunIdGetQueryKey = (runId?: string,) => {
    return [
    `/api/v1/runs/${runId}`
    ] as const;
    }

    
export const getGetRunApiV1RunsRunIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getRunApiV1RunsRunIdGet>>, TError = HTTPValidationError>(runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRunApiV1RunsRunIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRunApiV1RunsRunIdGetQueryKey(runId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRunApiV1RunsRunIdGet>>> = ({ signal }) => getRunApiV1RunsRunIdGet(runId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(runId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRunApiV1RunsRunIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRunApiV1RunsRunIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getRunApiV1RunsRunIdGet>>>
export type GetRunApiV1RunsRunIdGetQueryError = HTTPValidationError


export function useGetRunApiV1RunsRunIdGet<TData = Awaited<ReturnType<typeof getRunApiV1RunsRunIdGet>>, TError = HTTPValidationError>(
 runId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRunApiV1RunsRunIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRunApiV1RunsRunIdGet>>,
          TError,
          Awaited<ReturnType<typeof getRunApiV1RunsRunIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRunApiV1RunsRunIdGet<TData = Awaited<ReturnType<typeof getRunApiV1RunsRunIdGet>>, TError = HTTPValidationError>(
 runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRunApiV1RunsRunIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRunApiV1RunsRunIdGet>>,
          TError,
          Awaited<ReturnType<typeof getRunApiV1RunsRunIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRunApiV1RunsRunIdGet<TData = Awaited<ReturnType<typeof getRunApiV1RunsRunIdGet>>, TError = HTTPValidationError>(
 runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRunApiV1RunsRunIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Run
 */

export function useGetRunApiV1RunsRunIdGet<TData = Awaited<ReturnType<typeof getRunApiV1RunsRunIdGet>>, TError = HTTPValidationError>(
 runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRunApiV1RunsRunIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRunApiV1RunsRunIdGetQueryOptions(runId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * `sort_by` and `filters` name columns a Protocol declares, so which names
are legal is decided in the use case -- this function only parses the wire
format. `sort_dir` is a Literal, so FastAPI rejects anything else itself.
 * @summary Get Run Results
 */
export const getRunResultsApiV1RunsRunIdResultsGet = (
    runId: string,
    params?: GetRunResultsApiV1RunsRunIdResultsGetParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PaginatedResponsePredictionResponse>(
      {url: `/api/v1/runs/${runId}/results`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetRunResultsApiV1RunsRunIdResultsGetQueryKey = (runId?: string,
    params?: GetRunResultsApiV1RunsRunIdResultsGetParams,) => {
    return [
    `/api/v1/runs/${runId}/results`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetRunResultsApiV1RunsRunIdResultsGetQueryOptions = <TData = Awaited<ReturnType<typeof getRunResultsApiV1RunsRunIdResultsGet>>, TError = HTTPValidationError>(runId: string,
    params?: GetRunResultsApiV1RunsRunIdResultsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRunResultsApiV1RunsRunIdResultsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRunResultsApiV1RunsRunIdResultsGetQueryKey(runId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRunResultsApiV1RunsRunIdResultsGet>>> = ({ signal }) => getRunResultsApiV1RunsRunIdResultsGet(runId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(runId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRunResultsApiV1RunsRunIdResultsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRunResultsApiV1RunsRunIdResultsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getRunResultsApiV1RunsRunIdResultsGet>>>
export type GetRunResultsApiV1RunsRunIdResultsGetQueryError = HTTPValidationError


export function useGetRunResultsApiV1RunsRunIdResultsGet<TData = Awaited<ReturnType<typeof getRunResultsApiV1RunsRunIdResultsGet>>, TError = HTTPValidationError>(
 runId: string,
    params: undefined |  GetRunResultsApiV1RunsRunIdResultsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRunResultsApiV1RunsRunIdResultsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRunResultsApiV1RunsRunIdResultsGet>>,
          TError,
          Awaited<ReturnType<typeof getRunResultsApiV1RunsRunIdResultsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRunResultsApiV1RunsRunIdResultsGet<TData = Awaited<ReturnType<typeof getRunResultsApiV1RunsRunIdResultsGet>>, TError = HTTPValidationError>(
 runId: string,
    params?: GetRunResultsApiV1RunsRunIdResultsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRunResultsApiV1RunsRunIdResultsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRunResultsApiV1RunsRunIdResultsGet>>,
          TError,
          Awaited<ReturnType<typeof getRunResultsApiV1RunsRunIdResultsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRunResultsApiV1RunsRunIdResultsGet<TData = Awaited<ReturnType<typeof getRunResultsApiV1RunsRunIdResultsGet>>, TError = HTTPValidationError>(
 runId: string,
    params?: GetRunResultsApiV1RunsRunIdResultsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRunResultsApiV1RunsRunIdResultsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Run Results
 */

export function useGetRunResultsApiV1RunsRunIdResultsGet<TData = Awaited<ReturnType<typeof getRunResultsApiV1RunsRunIdResultsGet>>, TError = HTTPValidationError>(
 runId: string,
    params?: GetRunResultsApiV1RunsRunIdResultsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRunResultsApiV1RunsRunIdResultsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRunResultsApiV1RunsRunIdResultsGetQueryOptions(runId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Cancel Run
 */
export const cancelRunApiV1RunsRunIdCancelPost = (
    runId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/runs/${runId}/cancel`, method: 'POST', signal
    },
      );
    }
  


export const getCancelRunApiV1RunsRunIdCancelPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelRunApiV1RunsRunIdCancelPost>>, TError,{runId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof cancelRunApiV1RunsRunIdCancelPost>>, TError,{runId: string}, TContext> => {

const mutationKey = ['cancelRunApiV1RunsRunIdCancelPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cancelRunApiV1RunsRunIdCancelPost>>, {runId: string}> = (props) => {
          const {runId} = props ?? {};

          return  cancelRunApiV1RunsRunIdCancelPost(runId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CancelRunApiV1RunsRunIdCancelPostMutationResult = NonNullable<Awaited<ReturnType<typeof cancelRunApiV1RunsRunIdCancelPost>>>
    
    export type CancelRunApiV1RunsRunIdCancelPostMutationError = HTTPValidationError

    /**
 * @summary Cancel Run
 */
export const useCancelRunApiV1RunsRunIdCancelPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelRunApiV1RunsRunIdCancelPost>>, TError,{runId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cancelRunApiV1RunsRunIdCancelPost>>,
        TError,
        {runId: string},
        TContext
      > => {

      const mutationOptions = getCancelRunApiV1RunsRunIdCancelPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    