/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * daikon-studio
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateRunnerBody,
  CreatedRunnerResponse,
  HTTPValidationError,
  RunnerResponse
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * @summary List Runners
 */
export const listRunnersApiV1RunnersGet = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<RunnerResponse[]>(
      {url: `/api/v1/runners`, method: 'GET', signal
    },
      );
    }
  



export const getListRunnersApiV1RunnersGetQueryKey = () => {
    return [
    `/api/v1/runners`
    ] as const;
    }

    
export const getListRunnersApiV1RunnersGetQueryOptions = <TData = Awaited<ReturnType<typeof listRunnersApiV1RunnersGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRunnersApiV1RunnersGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListRunnersApiV1RunnersGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listRunnersApiV1RunnersGet>>> = ({ signal }) => listRunnersApiV1RunnersGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listRunnersApiV1RunnersGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListRunnersApiV1RunnersGetQueryResult = NonNullable<Awaited<ReturnType<typeof listRunnersApiV1RunnersGet>>>
export type ListRunnersApiV1RunnersGetQueryError = unknown


export function useListRunnersApiV1RunnersGet<TData = Awaited<ReturnType<typeof listRunnersApiV1RunnersGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRunnersApiV1RunnersGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRunnersApiV1RunnersGet>>,
          TError,
          Awaited<ReturnType<typeof listRunnersApiV1RunnersGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListRunnersApiV1RunnersGet<TData = Awaited<ReturnType<typeof listRunnersApiV1RunnersGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRunnersApiV1RunnersGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRunnersApiV1RunnersGet>>,
          TError,
          Awaited<ReturnType<typeof listRunnersApiV1RunnersGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListRunnersApiV1RunnersGet<TData = Awaited<ReturnType<typeof listRunnersApiV1RunnersGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRunnersApiV1RunnersGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Runners
 */

export function useListRunnersApiV1RunnersGet<TData = Awaited<ReturnType<typeof listRunnersApiV1RunnersGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRunnersApiV1RunnersGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListRunnersApiV1RunnersGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create Runner
 */
export const createRunnerApiV1RunnersPost = (
    createRunnerBody: CreateRunnerBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CreatedRunnerResponse>(
      {url: `/api/v1/runners`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createRunnerBody, signal
    },
      );
    }
  


export const getCreateRunnerApiV1RunnersPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRunnerApiV1RunnersPost>>, TError,{data: CreateRunnerBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createRunnerApiV1RunnersPost>>, TError,{data: CreateRunnerBody}, TContext> => {

const mutationKey = ['createRunnerApiV1RunnersPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createRunnerApiV1RunnersPost>>, {data: CreateRunnerBody}> = (props) => {
          const {data} = props ?? {};

          return  createRunnerApiV1RunnersPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateRunnerApiV1RunnersPostMutationResult = NonNullable<Awaited<ReturnType<typeof createRunnerApiV1RunnersPost>>>
    export type CreateRunnerApiV1RunnersPostMutationBody = CreateRunnerBody
    export type CreateRunnerApiV1RunnersPostMutationError = HTTPValidationError

    /**
 * @summary Create Runner
 */
export const useCreateRunnerApiV1RunnersPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRunnerApiV1RunnersPost>>, TError,{data: CreateRunnerBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createRunnerApiV1RunnersPost>>,
        TError,
        {data: CreateRunnerBody},
        TContext
      > => {

      const mutationOptions = getCreateRunnerApiV1RunnersPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Revoke Runner
 */
export const revokeRunnerApiV1RunnersRunnerIdRevokePost = (
    runnerId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/runners/${runnerId}/revoke`, method: 'POST', signal
    },
      );
    }
  


export const getRevokeRunnerApiV1RunnersRunnerIdRevokePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokeRunnerApiV1RunnersRunnerIdRevokePost>>, TError,{runnerId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof revokeRunnerApiV1RunnersRunnerIdRevokePost>>, TError,{runnerId: string}, TContext> => {

const mutationKey = ['revokeRunnerApiV1RunnersRunnerIdRevokePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof revokeRunnerApiV1RunnersRunnerIdRevokePost>>, {runnerId: string}> = (props) => {
          const {runnerId} = props ?? {};

          return  revokeRunnerApiV1RunnersRunnerIdRevokePost(runnerId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RevokeRunnerApiV1RunnersRunnerIdRevokePostMutationResult = NonNullable<Awaited<ReturnType<typeof revokeRunnerApiV1RunnersRunnerIdRevokePost>>>
    
    export type RevokeRunnerApiV1RunnersRunnerIdRevokePostMutationError = HTTPValidationError

    /**
 * @summary Revoke Runner
 */
export const useRevokeRunnerApiV1RunnersRunnerIdRevokePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokeRunnerApiV1RunnersRunnerIdRevokePost>>, TError,{runnerId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof revokeRunnerApiV1RunnersRunnerIdRevokePost>>,
        TError,
        {runnerId: string},
        TContext
      > => {

      const mutationOptions = getRevokeRunnerApiV1RunnersRunnerIdRevokePostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    