/**
 * Generated by orval. Do not edit manually.
 * daikon-studio
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ArchivePageBody,
  BodyUploadPageBlobApiV1PagesBlobsPost,
  CreatePageBody,
  GetPageContentApiV1PagesPageIdContentSha256Get200,
  HTTPValidationError,
  ListPagesApiV1PagesGetParams,
  PageBlobResponse,
  PageResponse,
  RetitlePageBody,
  RevisePageBody,
  RevisionResponse
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * The owner's pages, newest-updated first. `archived=true` lists only archived ones.
 * @summary List Pages
 */
export const listPagesApiV1PagesGet = (
    params: ListPagesApiV1PagesGetParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PageResponse[]>(
      {url: `/api/v1/pages`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListPagesApiV1PagesGetQueryKey = (params?: ListPagesApiV1PagesGetParams,) => {
    return [
    `/api/v1/pages`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListPagesApiV1PagesGetQueryOptions = <TData = Awaited<ReturnType<typeof listPagesApiV1PagesGet>>, TError = HTTPValidationError>(params: ListPagesApiV1PagesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPagesApiV1PagesGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPagesApiV1PagesGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPagesApiV1PagesGet>>> = ({ signal }) => listPagesApiV1PagesGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPagesApiV1PagesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPagesApiV1PagesGetQueryResult = NonNullable<Awaited<ReturnType<typeof listPagesApiV1PagesGet>>>
export type ListPagesApiV1PagesGetQueryError = HTTPValidationError


export function useListPagesApiV1PagesGet<TData = Awaited<ReturnType<typeof listPagesApiV1PagesGet>>, TError = HTTPValidationError>(
 params: ListPagesApiV1PagesGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPagesApiV1PagesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPagesApiV1PagesGet>>,
          TError,
          Awaited<ReturnType<typeof listPagesApiV1PagesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPagesApiV1PagesGet<TData = Awaited<ReturnType<typeof listPagesApiV1PagesGet>>, TError = HTTPValidationError>(
 params: ListPagesApiV1PagesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPagesApiV1PagesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPagesApiV1PagesGet>>,
          TError,
          Awaited<ReturnType<typeof listPagesApiV1PagesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPagesApiV1PagesGet<TData = Awaited<ReturnType<typeof listPagesApiV1PagesGet>>, TError = HTTPValidationError>(
 params: ListPagesApiV1PagesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPagesApiV1PagesGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Pages
 */

export function useListPagesApiV1PagesGet<TData = Awaited<ReturnType<typeof listPagesApiV1PagesGet>>, TError = HTTPValidationError>(
 params: ListPagesApiV1PagesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPagesApiV1PagesGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListPagesApiV1PagesGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create Page
 */
export const createPageApiV1PagesPost = (
    createPageBody: CreatePageBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PageResponse>(
      {url: `/api/v1/pages`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPageBody, signal
    },
      );
    }
  


export const getCreatePageApiV1PagesPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPageApiV1PagesPost>>, TError,{data: CreatePageBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createPageApiV1PagesPost>>, TError,{data: CreatePageBody}, TContext> => {

const mutationKey = ['createPageApiV1PagesPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPageApiV1PagesPost>>, {data: CreatePageBody}> = (props) => {
          const {data} = props ?? {};

          return  createPageApiV1PagesPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePageApiV1PagesPostMutationResult = NonNullable<Awaited<ReturnType<typeof createPageApiV1PagesPost>>>
    export type CreatePageApiV1PagesPostMutationBody = CreatePageBody
    export type CreatePageApiV1PagesPostMutationError = HTTPValidationError

    /**
 * @summary Create Page
 */
export const useCreatePageApiV1PagesPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPageApiV1PagesPost>>, TError,{data: CreatePageBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPageApiV1PagesPost>>,
        TError,
        {data: CreatePageBody},
        TContext
      > => {

      const mutationOptions = getCreatePageApiV1PagesPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * An image to embed in a page: PNG, JPEG, GIF, WebP or SVG.
 * @summary Upload Page Blob
 */
export const uploadPageBlobApiV1PagesBlobsPost = (
    bodyUploadPageBlobApiV1PagesBlobsPost: BodyUploadPageBlobApiV1PagesBlobsPost,
 signal?: AbortSignal
) => {
      
      const formData = new FormData();
formData.append(`file`, bodyUploadPageBlobApiV1PagesBlobsPost.file)

      return customInstance<PageBlobResponse>(
      {url: `/api/v1/pages/blobs`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData, signal
    },
      );
    }
  


export const getUploadPageBlobApiV1PagesBlobsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadPageBlobApiV1PagesBlobsPost>>, TError,{data: BodyUploadPageBlobApiV1PagesBlobsPost}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof uploadPageBlobApiV1PagesBlobsPost>>, TError,{data: BodyUploadPageBlobApiV1PagesBlobsPost}, TContext> => {

const mutationKey = ['uploadPageBlobApiV1PagesBlobsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadPageBlobApiV1PagesBlobsPost>>, {data: BodyUploadPageBlobApiV1PagesBlobsPost}> = (props) => {
          const {data} = props ?? {};

          return  uploadPageBlobApiV1PagesBlobsPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UploadPageBlobApiV1PagesBlobsPostMutationResult = NonNullable<Awaited<ReturnType<typeof uploadPageBlobApiV1PagesBlobsPost>>>
    export type UploadPageBlobApiV1PagesBlobsPostMutationBody = BodyUploadPageBlobApiV1PagesBlobsPost
    export type UploadPageBlobApiV1PagesBlobsPostMutationError = HTTPValidationError

    /**
 * @summary Upload Page Blob
 */
export const useUploadPageBlobApiV1PagesBlobsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadPageBlobApiV1PagesBlobsPost>>, TError,{data: BodyUploadPageBlobApiV1PagesBlobsPost}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadPageBlobApiV1PagesBlobsPost>>,
        TError,
        {data: BodyUploadPageBlobApiV1PagesBlobsPost},
        TContext
      > => {

      const mutationOptions = getUploadPageBlobApiV1PagesBlobsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Served as a download in a sandbox, so a file that slipped through as something
else cannot run in the studio's origin when opened directly.
 * @summary Get Page Blob
 */
export const getPageBlobApiV1PagesBlobsSha256Get = (
    sha256: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/pages/blobs/${sha256}`, method: 'GET', signal
    },
      );
    }
  



export const getGetPageBlobApiV1PagesBlobsSha256GetQueryKey = (sha256?: string,) => {
    return [
    `/api/v1/pages/blobs/${sha256}`
    ] as const;
    }

    
export const getGetPageBlobApiV1PagesBlobsSha256GetQueryOptions = <TData = Awaited<ReturnType<typeof getPageBlobApiV1PagesBlobsSha256Get>>, TError = HTTPValidationError>(sha256: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPageBlobApiV1PagesBlobsSha256Get>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPageBlobApiV1PagesBlobsSha256GetQueryKey(sha256);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPageBlobApiV1PagesBlobsSha256Get>>> = ({ signal }) => getPageBlobApiV1PagesBlobsSha256Get(sha256, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(sha256), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPageBlobApiV1PagesBlobsSha256Get>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPageBlobApiV1PagesBlobsSha256GetQueryResult = NonNullable<Awaited<ReturnType<typeof getPageBlobApiV1PagesBlobsSha256Get>>>
export type GetPageBlobApiV1PagesBlobsSha256GetQueryError = HTTPValidationError


export function useGetPageBlobApiV1PagesBlobsSha256Get<TData = Awaited<ReturnType<typeof getPageBlobApiV1PagesBlobsSha256Get>>, TError = HTTPValidationError>(
 sha256: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPageBlobApiV1PagesBlobsSha256Get>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPageBlobApiV1PagesBlobsSha256Get>>,
          TError,
          Awaited<ReturnType<typeof getPageBlobApiV1PagesBlobsSha256Get>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPageBlobApiV1PagesBlobsSha256Get<TData = Awaited<ReturnType<typeof getPageBlobApiV1PagesBlobsSha256Get>>, TError = HTTPValidationError>(
 sha256: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPageBlobApiV1PagesBlobsSha256Get>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPageBlobApiV1PagesBlobsSha256Get>>,
          TError,
          Awaited<ReturnType<typeof getPageBlobApiV1PagesBlobsSha256Get>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPageBlobApiV1PagesBlobsSha256Get<TData = Awaited<ReturnType<typeof getPageBlobApiV1PagesBlobsSha256Get>>, TError = HTTPValidationError>(
 sha256: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPageBlobApiV1PagesBlobsSha256Get>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Page Blob
 */

export function useGetPageBlobApiV1PagesBlobsSha256Get<TData = Awaited<ReturnType<typeof getPageBlobApiV1PagesBlobsSha256Get>>, TError = HTTPValidationError>(
 sha256: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPageBlobApiV1PagesBlobsSha256Get>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPageBlobApiV1PagesBlobsSha256GetQueryOptions(sha256,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get Page
 */
export const getPageApiV1PagesPageIdGet = (
    pageId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PageResponse>(
      {url: `/api/v1/pages/${pageId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetPageApiV1PagesPageIdGetQueryKey = (pageId?: string,) => {
    return [
    `/api/v1/pages/${pageId}`
    ] as const;
    }

    
export const getGetPageApiV1PagesPageIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getPageApiV1PagesPageIdGet>>, TError = HTTPValidationError>(pageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPageApiV1PagesPageIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPageApiV1PagesPageIdGetQueryKey(pageId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPageApiV1PagesPageIdGet>>> = ({ signal }) => getPageApiV1PagesPageIdGet(pageId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(pageId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPageApiV1PagesPageIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPageApiV1PagesPageIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getPageApiV1PagesPageIdGet>>>
export type GetPageApiV1PagesPageIdGetQueryError = HTTPValidationError


export function useGetPageApiV1PagesPageIdGet<TData = Awaited<ReturnType<typeof getPageApiV1PagesPageIdGet>>, TError = HTTPValidationError>(
 pageId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPageApiV1PagesPageIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPageApiV1PagesPageIdGet>>,
          TError,
          Awaited<ReturnType<typeof getPageApiV1PagesPageIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPageApiV1PagesPageIdGet<TData = Awaited<ReturnType<typeof getPageApiV1PagesPageIdGet>>, TError = HTTPValidationError>(
 pageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPageApiV1PagesPageIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPageApiV1PagesPageIdGet>>,
          TError,
          Awaited<ReturnType<typeof getPageApiV1PagesPageIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPageApiV1PagesPageIdGet<TData = Awaited<ReturnType<typeof getPageApiV1PagesPageIdGet>>, TError = HTTPValidationError>(
 pageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPageApiV1PagesPageIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Page
 */

export function useGetPageApiV1PagesPageIdGet<TData = Awaited<ReturnType<typeof getPageApiV1PagesPageIdGet>>, TError = HTTPValidationError>(
 pageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPageApiV1PagesPageIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPageApiV1PagesPageIdGetQueryOptions(pageId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Save a new body. 409 if the page moved past `expected_version`; saving the body it
already has changes nothing.
 * @summary Revise Page
 */
export const revisePageApiV1PagesPageIdPatch = (
    pageId: string,
    revisePageBody: RevisePageBody,
 ) => {
      
      
      return customInstance<PageResponse>(
      {url: `/api/v1/pages/${pageId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: revisePageBody
    },
      );
    }
  


export const getRevisePageApiV1PagesPageIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revisePageApiV1PagesPageIdPatch>>, TError,{pageId: string;data: RevisePageBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof revisePageApiV1PagesPageIdPatch>>, TError,{pageId: string;data: RevisePageBody}, TContext> => {

const mutationKey = ['revisePageApiV1PagesPageIdPatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof revisePageApiV1PagesPageIdPatch>>, {pageId: string;data: RevisePageBody}> = (props) => {
          const {pageId,data} = props ?? {};

          return  revisePageApiV1PagesPageIdPatch(pageId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RevisePageApiV1PagesPageIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof revisePageApiV1PagesPageIdPatch>>>
    export type RevisePageApiV1PagesPageIdPatchMutationBody = RevisePageBody
    export type RevisePageApiV1PagesPageIdPatchMutationError = HTTPValidationError

    /**
 * @summary Revise Page
 */
export const useRevisePageApiV1PagesPageIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revisePageApiV1PagesPageIdPatch>>, TError,{pageId: string;data: RevisePageBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof revisePageApiV1PagesPageIdPatch>>,
        TError,
        {pageId: string;data: RevisePageBody},
        TContext
      > => {

      const mutationOptions = getRevisePageApiV1PagesPageIdPatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete Page
 */
export const deletePageApiV1PagesPageIdDelete = (
    pageId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/pages/${pageId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeletePageApiV1PagesPageIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePageApiV1PagesPageIdDelete>>, TError,{pageId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deletePageApiV1PagesPageIdDelete>>, TError,{pageId: string}, TContext> => {

const mutationKey = ['deletePageApiV1PagesPageIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePageApiV1PagesPageIdDelete>>, {pageId: string}> = (props) => {
          const {pageId} = props ?? {};

          return  deletePageApiV1PagesPageIdDelete(pageId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeletePageApiV1PagesPageIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deletePageApiV1PagesPageIdDelete>>>
    
    export type DeletePageApiV1PagesPageIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Page
 */
export const useDeletePageApiV1PagesPageIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePageApiV1PagesPageIdDelete>>, TError,{pageId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePageApiV1PagesPageIdDelete>>,
        TError,
        {pageId: string},
        TContext
      > => {

      const mutationOptions = getDeletePageApiV1PagesPageIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Retitle Page
 */
export const retitlePageApiV1PagesPageIdTitlePut = (
    pageId: string,
    retitlePageBody: RetitlePageBody,
 ) => {
      
      
      return customInstance<PageResponse>(
      {url: `/api/v1/pages/${pageId}/title`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: retitlePageBody
    },
      );
    }
  


export const getRetitlePageApiV1PagesPageIdTitlePutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof retitlePageApiV1PagesPageIdTitlePut>>, TError,{pageId: string;data: RetitlePageBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof retitlePageApiV1PagesPageIdTitlePut>>, TError,{pageId: string;data: RetitlePageBody}, TContext> => {

const mutationKey = ['retitlePageApiV1PagesPageIdTitlePut'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof retitlePageApiV1PagesPageIdTitlePut>>, {pageId: string;data: RetitlePageBody}> = (props) => {
          const {pageId,data} = props ?? {};

          return  retitlePageApiV1PagesPageIdTitlePut(pageId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RetitlePageApiV1PagesPageIdTitlePutMutationResult = NonNullable<Awaited<ReturnType<typeof retitlePageApiV1PagesPageIdTitlePut>>>
    export type RetitlePageApiV1PagesPageIdTitlePutMutationBody = RetitlePageBody
    export type RetitlePageApiV1PagesPageIdTitlePutMutationError = HTTPValidationError

    /**
 * @summary Retitle Page
 */
export const useRetitlePageApiV1PagesPageIdTitlePut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof retitlePageApiV1PagesPageIdTitlePut>>, TError,{pageId: string;data: RetitlePageBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof retitlePageApiV1PagesPageIdTitlePut>>,
        TError,
        {pageId: string;data: RetitlePageBody},
        TContext
      > => {

      const mutationOptions = getRetitlePageApiV1PagesPageIdTitlePutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Archive Page
 */
export const archivePageApiV1PagesPageIdArchivePost = (
    pageId: string,
    archivePageBody: ArchivePageBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PageResponse>(
      {url: `/api/v1/pages/${pageId}/archive`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: archivePageBody, signal
    },
      );
    }
  


export const getArchivePageApiV1PagesPageIdArchivePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof archivePageApiV1PagesPageIdArchivePost>>, TError,{pageId: string;data: ArchivePageBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof archivePageApiV1PagesPageIdArchivePost>>, TError,{pageId: string;data: ArchivePageBody}, TContext> => {

const mutationKey = ['archivePageApiV1PagesPageIdArchivePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof archivePageApiV1PagesPageIdArchivePost>>, {pageId: string;data: ArchivePageBody}> = (props) => {
          const {pageId,data} = props ?? {};

          return  archivePageApiV1PagesPageIdArchivePost(pageId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ArchivePageApiV1PagesPageIdArchivePostMutationResult = NonNullable<Awaited<ReturnType<typeof archivePageApiV1PagesPageIdArchivePost>>>
    export type ArchivePageApiV1PagesPageIdArchivePostMutationBody = ArchivePageBody
    export type ArchivePageApiV1PagesPageIdArchivePostMutationError = HTTPValidationError

    /**
 * @summary Archive Page
 */
export const useArchivePageApiV1PagesPageIdArchivePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof archivePageApiV1PagesPageIdArchivePost>>, TError,{pageId: string;data: ArchivePageBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof archivePageApiV1PagesPageIdArchivePost>>,
        TError,
        {pageId: string;data: ArchivePageBody},
        TContext
      > => {

      const mutationOptions = getArchivePageApiV1PagesPageIdArchivePostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Oldest first.
 * @summary List Page Revisions
 */
export const listPageRevisionsApiV1PagesPageIdRevisionsGet = (
    pageId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<RevisionResponse[]>(
      {url: `/api/v1/pages/${pageId}/revisions`, method: 'GET', signal
    },
      );
    }
  



export const getListPageRevisionsApiV1PagesPageIdRevisionsGetQueryKey = (pageId?: string,) => {
    return [
    `/api/v1/pages/${pageId}/revisions`
    ] as const;
    }

    
export const getListPageRevisionsApiV1PagesPageIdRevisionsGetQueryOptions = <TData = Awaited<ReturnType<typeof listPageRevisionsApiV1PagesPageIdRevisionsGet>>, TError = HTTPValidationError>(pageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPageRevisionsApiV1PagesPageIdRevisionsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPageRevisionsApiV1PagesPageIdRevisionsGetQueryKey(pageId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPageRevisionsApiV1PagesPageIdRevisionsGet>>> = ({ signal }) => listPageRevisionsApiV1PagesPageIdRevisionsGet(pageId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(pageId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPageRevisionsApiV1PagesPageIdRevisionsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPageRevisionsApiV1PagesPageIdRevisionsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listPageRevisionsApiV1PagesPageIdRevisionsGet>>>
export type ListPageRevisionsApiV1PagesPageIdRevisionsGetQueryError = HTTPValidationError


export function useListPageRevisionsApiV1PagesPageIdRevisionsGet<TData = Awaited<ReturnType<typeof listPageRevisionsApiV1PagesPageIdRevisionsGet>>, TError = HTTPValidationError>(
 pageId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPageRevisionsApiV1PagesPageIdRevisionsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPageRevisionsApiV1PagesPageIdRevisionsGet>>,
          TError,
          Awaited<ReturnType<typeof listPageRevisionsApiV1PagesPageIdRevisionsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPageRevisionsApiV1PagesPageIdRevisionsGet<TData = Awaited<ReturnType<typeof listPageRevisionsApiV1PagesPageIdRevisionsGet>>, TError = HTTPValidationError>(
 pageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPageRevisionsApiV1PagesPageIdRevisionsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPageRevisionsApiV1PagesPageIdRevisionsGet>>,
          TError,
          Awaited<ReturnType<typeof listPageRevisionsApiV1PagesPageIdRevisionsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPageRevisionsApiV1PagesPageIdRevisionsGet<TData = Awaited<ReturnType<typeof listPageRevisionsApiV1PagesPageIdRevisionsGet>>, TError = HTTPValidationError>(
 pageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPageRevisionsApiV1PagesPageIdRevisionsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Page Revisions
 */

export function useListPageRevisionsApiV1PagesPageIdRevisionsGet<TData = Awaited<ReturnType<typeof listPageRevisionsApiV1PagesPageIdRevisionsGet>>, TError = HTTPValidationError>(
 pageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPageRevisionsApiV1PagesPageIdRevisionsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListPageRevisionsApiV1PagesPageIdRevisionsGetQueryOptions(pageId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * One revision's document, by the sha256 the revision list names.
 * @summary Get Page Content
 */
export const getPageContentApiV1PagesPageIdContentSha256Get = (
    pageId: string,
    sha256: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<GetPageContentApiV1PagesPageIdContentSha256Get200>(
      {url: `/api/v1/pages/${pageId}/content/${sha256}`, method: 'GET', signal
    },
      );
    }
  



export const getGetPageContentApiV1PagesPageIdContentSha256GetQueryKey = (pageId?: string,
    sha256?: string,) => {
    return [
    `/api/v1/pages/${pageId}/content/${sha256}`
    ] as const;
    }

    
export const getGetPageContentApiV1PagesPageIdContentSha256GetQueryOptions = <TData = Awaited<ReturnType<typeof getPageContentApiV1PagesPageIdContentSha256Get>>, TError = HTTPValidationError>(pageId: string,
    sha256: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPageContentApiV1PagesPageIdContentSha256Get>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPageContentApiV1PagesPageIdContentSha256GetQueryKey(pageId,sha256);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPageContentApiV1PagesPageIdContentSha256Get>>> = ({ signal }) => getPageContentApiV1PagesPageIdContentSha256Get(pageId,sha256, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(pageId && sha256), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPageContentApiV1PagesPageIdContentSha256Get>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPageContentApiV1PagesPageIdContentSha256GetQueryResult = NonNullable<Awaited<ReturnType<typeof getPageContentApiV1PagesPageIdContentSha256Get>>>
export type GetPageContentApiV1PagesPageIdContentSha256GetQueryError = HTTPValidationError


export function useGetPageContentApiV1PagesPageIdContentSha256Get<TData = Awaited<ReturnType<typeof getPageContentApiV1PagesPageIdContentSha256Get>>, TError = HTTPValidationError>(
 pageId: string,
    sha256: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPageContentApiV1PagesPageIdContentSha256Get>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPageContentApiV1PagesPageIdContentSha256Get>>,
          TError,
          Awaited<ReturnType<typeof getPageContentApiV1PagesPageIdContentSha256Get>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPageContentApiV1PagesPageIdContentSha256Get<TData = Awaited<ReturnType<typeof getPageContentApiV1PagesPageIdContentSha256Get>>, TError = HTTPValidationError>(
 pageId: string,
    sha256: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPageContentApiV1PagesPageIdContentSha256Get>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPageContentApiV1PagesPageIdContentSha256Get>>,
          TError,
          Awaited<ReturnType<typeof getPageContentApiV1PagesPageIdContentSha256Get>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPageContentApiV1PagesPageIdContentSha256Get<TData = Awaited<ReturnType<typeof getPageContentApiV1PagesPageIdContentSha256Get>>, TError = HTTPValidationError>(
 pageId: string,
    sha256: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPageContentApiV1PagesPageIdContentSha256Get>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Page Content
 */

export function useGetPageContentApiV1PagesPageIdContentSha256Get<TData = Awaited<ReturnType<typeof getPageContentApiV1PagesPageIdContentSha256Get>>, TError = HTTPValidationError>(
 pageId: string,
    sha256: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPageContentApiV1PagesPageIdContentSha256Get>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPageContentApiV1PagesPageIdContentSha256GetQueryOptions(pageId,sha256,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




